export const MAINSTREAM_SCHOOL_OPTIONS: string[] = [
  "Abbotsford Primary School - Abbotsford - 3067",
  "Aberfeldie Primary School - Essendon - 3040",
  "Academy of Mary Immaculate - Fitzroy - 3065",
  "Adass Israel School - Elsternwick - 3185",
  "Adass Israel School - Glen Eira Road Campus - Elsternwick - 3185",
  "Adass Israel School - Orrong Road Campus - Elsternwick - 3185",
  "Advance College of Education Incorporated - Hastings Hub - Hastings - 3915",
  "Advance College of Education Incorporated - Mornington Campus - Mornington - 3931",
  "Advance College of Education Incorporated - Rosebud West - 3940",
  "Ainslie Parklands Primary School - Croydon - 3136",
  "Aintree Primary School - Aintree - 3336",
  "Aitken College - Greenvale - 3059",
  "Aitken Creek Primary School - Craigieburn - 3064",
  "Aitken Hill Primary School - Craigieburn - 3064",
  "Al Iman College - Melton South - 3338",
  "Al Siraat College - Epping - 3076",
  "Alamanda K-9 College - Point Cook - 3030",
  "Albanvale Primary School - Albanvale - 3021",
  "Albany Rise Primary School - Mulgrave - 3170",
  "Albert Park College - Albert Park - 3206",
  "Albert Park College-Environmental Arts Hub - Albert Park - 3207",
  "Albert Park Primary School - Albert Park - 3206",
  "Albion North Primary School - Sunshine North - 3020",
  "Albion Primary School - Albion - 3020",
  "Aldercourt Primary School - Frankston North - 3200",
  "Alia College - Hawthorn East - 3123",
  "Alkira Secondary College - Cranbourne North - 3977",
  "Alphington Grammar School - Alphington - 3078",
  "Alphington Primary School - Alphington - 3078",
  "Al-Taqwa College - Hoppers Crossing - 3029",
  "Al-Taqwa College - Olive Branch Annexe - Hoppers Crossing - 3029",
  "Altona College - Altona - 3018",
  "Altona Green Primary School - Altona Meadows - 3028",
  "Altona Meadows Primary School - Altona Meadows - 3028",
  "Altona North Primary School - Altona North - 3025",
  "Altona Primary School - Altona - 3018",
  "Amsleigh Park Primary School - Oakleigh East - 3166",
  "Andale School - Kew - 3101",
  "Andersons Creek Primary School - Warrandyte - 3113",
  "Annunciation School - Brooklyn - 3012",
  "Antonine College - Cedar Campus - Coburg - 3058",
  "Antonine College - Pascoe Vale South - 3044",
  "Antonio Park Primary School - Mitcham - 3132",
  "Apollo Parkways Primary School - Greensborough - 3088",
  "Aquinas College - Ringwood - 3134",
  "Ardeer Primary School - Ardeer - 3022",
  "Ardeer South Primary School - Sunshine West - 3020",
  "Armadale Primary School - Armadale - 3143",
  "Armstrong Creek School - Armstrong Creek - 3217",
  "Armstrong Creek School - Specialist P-12 Campus - Armstrong Creek - 3218",
  "Arnolds Creek Primary School - Harkness - 3337",
  "Ascot Vale Heights School - Ascot Vale - 3032",
  "Ascot Vale Primary School - Ascot Vale - 3032",
  "Ascot Vale West Primary School - Ascot Vale - 3032",
  "Ashburton Primary School - Ashburton - 3147",
  "Ashby Primary School - Geelong West - 3218",
  "Ashley Park Primary School - Doreen - 3754",
  "Ashwood High School - Ashwood - 3147",
  "Ashwood School - Ashwood - 3147",
  "Aspendale Gardens Primary School - Aspendale Gardens - 3195",
  "Aspendale Primary School - Aspendale - 3195",
  "Athol Road Primary School - Springvale South - 3172",
  "Auburn High School - Hawthorn East - 3123",
  "Auburn Primary School - Hawthorn East - 3123",
  "Auburn South Primary School - Hawthorn East - 3123",
  "Aurora School - Blackburn South - 3130",
  "Austin Hospital School - Heidelberg - 3084",
  "Australian International Academy of Education - Caroline Springs Primary Campus - Caroline Springs - 3023",
  "Australian International Academy of Education - Caroline Springs Senior Campus - Caroline Springs - 3023",
  "Australian International Academy of Education - Coburg - 3058",
  "Australian International Academy of Education - Senior Campus - Coburg North - 3058",
  "Australis Christian College - Skye - 3977",
  "Ave Maria College - Aberfeldie - 3040",
  "Avenues Education - Eastern Metropolitan - Ringwood East - 3135",
  "Avenues Education - Moorabbin - 3189",
  "Avila College - Mount Waverley - 3149",
  "Avondale Primary School - Avondale Heights - 3034",
  "Bacchus Marsh College - Bacchus Marsh - 3340",
  "Bacchus Marsh Grammar - Maddingley Campus - Bacchus Marsh - 3340",
  "Bacchus Marsh Grammar - Woodlea - Aintree  - 3336",
  "Bacchus Marsh Primary School - Bacchus Marsh - 3340",
  "Baden Powell P-9 College - Hoppers Crossing - 3029",
  "Baden Powell P-9 College-Tarneit Campus - Tarneit - 3029",
  "Balcombe Grammar School - Mount Martha - 3934",
  "Ballam Park Primary School - Frankston - 3199",
  "Balnarring Primary School - Balnarring - 3926",
  "Balwyn High School - Balwyn North - 3104",
  "Balwyn North Primary School - Balwyn North - 3104",
  "Balwyn Primary School - Balwyn - 3103",
  "Banyan Fields Primary School - Carrum Downs - 3201",
  "Banyule Primary School - Rosanna - 3084",
  "Barton Primary School - Cranbourne West - 3977",
  "Barwon Valley School - Belmont - 3216",
  "Baxter Primary School - Baxter - 3911",
  "Bayside Christian College - Langwarrin South - 3911",
  "Bayside P-12 College - Williamstown - 3016",
  "Bayside P-12 College-Altona North Campus - Altona North - 3025",
  "Bayside P-12 College-Paisley Campus - Newport - 3015",
  "Bayside Special Developmental School - Moorabbin - 3189",
  "Bayswater North Primary School - Bayswater North - 3153",
  "Bayswater Primary School - Bayswater - 3153",
  "Bayswater Secondary College - Bayswater - 3153",
  "Bayswater South Primary School - Bayswater - 3153",
  "Bayswater West Primary School - Bayswater - 3153",
  "Beaconhills College - Pakenham - 3810",
  "Beaconhills College - Village Campus - Berwick - 3806",
  "Beaconsfield Primary School - Beaconsfield - 3807",
  "Beaconsfield Upper Primary School - Beaconsfield Upper - 3808",
  "Beaumaris North Primary School - Beaumaris - 3193",
  "Beaumaris Primary School - Beaumaris - 3193",
  "Beaumaris Secondary College - Beaumaris - 3193",
  "Belgrave Heights Christian School - Belgrave Heights - 3160",
  "Belgrave South Primary School - Belgrave South - 3160",
  "Bell Park North Primary School - Bell Park - 3215",
  "Bell Park North Primary School-Geelong English Language Program - Bell Park - 3215",
  "Bell Primary School - Preston - 3072",
  "Bellaire Primary School - Highton - 3216",
  "Bellbridge Primary School - Hoppers Crossing - 3029",
  "Belle Vue Park Primary School - Glenroy - 3046",
  "Belle Vue Primary School - Balwyn North - 3104",
  "Belmont High School - Belmont - 3216",
  "Belmont Primary School - Belmont - 3216",
  "Belmore School - Balwyn - 3103",
  "Belvedere Park Primary School - Seaford - 3198",
  "Bentleigh Secondary College - Bentleigh East - 3165",
  "Bentleigh West Primary School - Bentleigh - 3204",
  "Benton Junior College - Mornington - 3931",
  "Berendale School - Hampton East - 3188",
  "Berendale School-SMR Secondary Teaching Unit - Hampton East - 3188",
  "Berengarra School - Box Hill North - 3129",
  "Berengarra School - Café Education - Ashwood - 3147",
  "Berengarra School - Pathways Campus - Chadstone - 3148",
  "Berry Street School - Noble Park - 3174",
  "Berwick Chase Primary School - Berwick - 3806",
  "Berwick Fields Primary School - Berwick - 3806",
  "Berwick Lodge Primary School - Berwick - 3806",
  "Berwick Primary School - Berwick - 3806",
  "Berwick Secondary College - Berwick - 3806",
  "Beth Rivkah Ladies College - St Kilda East - 3183",
  "Bethal Primary School - Meadow Heights - 3048",
  "Bethany Catholic Primary School - Werribee - 3030",
  "Beveridge Primary School - Beveridge - 3753",
  "Beveridge Primary School-Ambrosia Campus - Beveridge - 3754",
  "Beverley Hills Primary School - Doncaster East - 3109",
  "Bialik College - Hawthorn - 3122",
  "Billanook College - Mooroolbark - 3138",
  "Billanook Primary School - Montrose - 3765",
  "Bimbadeen Heights Primary School - Mooroolbark - 3138",
  "Birmingham Primary School - Mount Evelyn - 3796",
  "Birralee Primary School - Doncaster - 3108",
  "Bittern Primary School - Bittern - 3918",
  "Black Rock Primary School - Black Rock - 3193",
  "Blackburn English Language School - Burwood East - 3151",
  "Blackburn English Language School-Maroondah Campus - Croydon North - 3136",
  "Blackburn High School - Blackburn - 3130",
  "Blackburn Lake Primary School - Blackburn - 3130",
  "Blackburn Primary School - Blackburn - 3130",
  "Bonbeach Primary School - Bonbeach - 3196",
  "Boronia Heights Primary School - Boronia - 3155",
  "Boronia K-12 College - Boronia - 3155",
  "Boronia West Primary School - Boronia - 3155",
  "Boroondara Park Primary School - Balwyn North - 3104",
  "Botanic Ridge Primary School - Botanic Ridge - 3977",
  "Box Hill High School - Box Hill - 3128",
  "Box Hill North Primary School - Box Hill North - 3129",
  "Box Hill Senior Secondary College - Mont Albert North - 3129",
  "Brandon Park Primary School - Wheelers Hill - 3150",
  "Braybrook College - Braybrook - 3019",
  "Brentwood Park Primary School - Berwick - 3806",
  "Brentwood Secondary College - Glen Waverley - 3150",
  "Briar Hill Primary School - Briar Hill - 3088",
  "Bridgewood Primary School - Officer - 3809",
  "Brighton Beach Primary School - Brighton - 3186",
  "Brighton Grammar School - Brighton - 3186",
  "Brighton Primary School - Brighton - 3186",
  "Brighton Primary School-Brighton Primary School Deaf Facility - Brighton - 3186",
  "Brighton Secondary College - Brighton East - 3187",
  "Broadmeadows Primary School - Broadmeadows - 3047",
  "Broadmeadows Special Developmental School - Broadmeadows - 3047",
  "Broadmeadows Special Developmental School-Sorrento Street Campus - Broadmeadows - 3047",
  "Broadmeadows Valley Primary School - Broadmeadows - 3047",
  "Broadmeadows Valley Primary School Meadowfair North Campus - Broadmeadows - 3047",
  "Brookside P-9 College - Caroline Springs - 3023",
  "Brunswick East Primary School - Brunswick East - 3057",
  "Brunswick North Primary School - Brunswick West - 3055",
  "Brunswick North West Primary School - Brunswick West - 3055",
  "Brunswick Secondary College - Brunswick - 3056",
  "Brunswick Secondary College-The Brunswick Learning Space - Brunswick South - 3055",
  "Brunswick South Primary School - Brunswick East - 3057",
  "Brunswick South West Primary School - Brunswick West - 3055",
  "Buckley Park College - Essendon - 3040",
  "Bulleen Heights School - Bulleen - 3105",
  "Bulleen Heights School-Manningham Road Campus - Lower Templestowe - 3107",
  "Bundoora Primary School - Bundoora - 3083",
  "Bundoora Secondary College - Bundoora - 3083",
  "Burnside Primary School - Burnside - 3023",
  "Burwood East Primary School - Burwood East - 3151",
  "Burwood East Special Developmental School - Burwood East - 3151",
  "Burwood Heights Primary School - Burwood East - 3151",
  "Cairnlea Park Primary School - Cairnlea - 3023",
  "Cairnlea Park Primary School-Western Special Assistance Unit - Language - Cairnlea - 3023",
  "Camberwell Girls Grammar School - Canterbury - 3126",
  "Camberwell Girls Grammar School - Junior Campus - Canterbury - 3126",
  "Camberwell Grammar School - Canterbury - 3126",
  "Camberwell High School - Canterbury - 3126",
  "Camberwell Primary School - Camberwell - 3124",
  "Camberwell South Primary School - Glen Iris - 3146",
  "Cambridge Primary School - Hoppers Crossing - 3029",
  "Camelot Rise Primary School - Glen Waverley - 3150",
  "Campbellfield Heights Primary School - Campbellfield - 3061",
  "Cana Catholic Primary School - Hillside - 3037",
  "Canterbury Girls Secondary College - Canterbury - 3126",
  "Canterbury Primary School - Canterbury - 3126",
  "Carey Baptist Grammar School - Donvale Campus - Donvale - 3111",
  "Carey Baptist Grammar School - Kew - 3101",
  "Carlton Gardens Primary School - Carlton - 3053",
  "Carlton North Primary School - Carlton North - 3054",
  "Carlton Primary School - Carlton - 3053",
  "Carnegie Primary School - Carnegie - 3163",
  "Caroline Chisholm Catholic College - Braybrook - 3019",
  "Caroline Chisholm Catholic College - Christ The King Campus - Braybrook - 3019",
  "Caroline Chisholm Catholic College - Sacred Heart Campus - Braybrook - 3019",
  "Carranballac P-9 College - Point Cook - 3030",
  "Carranballac P-9 College-Jamieson Way Campus - Point Cook - 3030",
  "Carrington Primary School - Knoxfield - 3180",
  "Carrum Downs Secondary College - Carrum Downs - 3201",
  "Carrum Primary School - Carrum - 3197",
  "Carwatha College P-12 - Noble Park - 3174",
  "Casey Fields Primary School - Cranbourne East - 3977",
  "Casey Grammar School - Cranbourne East - 3977",
  "Catholic Ladies' College Ltd - Eltham - 3095",
  "Catholic Regional College Caroline Springs - Caroline Springs - 3023",
  "Catholic Regional College Melton - Melton West - 3337",
  "Catholic Regional College North Keilor - Keilor Lodge - 3038",
  "Catholic Regional College St Albans - St Albans - 3021",
  "Catholic Regional College Sydenham - Sydenham - 3037",
  "Caulfield Grammar School - Malvern Campus - Glen Iris - 3146",
  "Caulfield Grammar School - St Kilda East - 3183",
  "Caulfield Grammar School - Wheelers Hill Campus - Wheelers Hill - 3150",
  "Caulfield Junior College - Caulfield North - 3161",
  "Caulfield Primary School - Caulfield South - 3162",
  "Caulfield South Primary School - Caulfield South - 3162",
  "Chalcot Lodge Primary School - Endeavour Hills - 3802",
  "Chandler Park Primary School - Keysborough - 3173",
  "Charles La Trobe P-12 College - Macleod West - 3085",
  "Charles La Trobe P-12 College-Deaf Facility - Macleod West - 3085",
  "Charles La Trobe P-12 College-Olympic Village Primary Campus - West Heidelberg - 3081",
  "Charles La Trobe P-12 College-Pavilion - The Edge South Morang Campus - Epping - 3082",
  "Charles La Trobe P-12 College-The Pavilion Campus - Preston East - Preston East - 3076",
  "Chatham Primary School - Surrey Hills - 3127",
  "Cheder Levi Yitzchok Inc - South Yarra - 3182",
  "Chelsea Heights Primary School - Chelsea Heights - 3196",
  "Chelsea Primary School - Chelsea - 3196",
  "Cheltenham East Primary School - Cheltenham - 3192",
  "Cheltenham Primary School - Cheltenham - 3192",
  "Cheltenham Secondary College - Cheltenham - 3192",
  "Cheshire School - Glen Waverley - 3150",
  "Chilwell Primary School - Newtown - 3220",
  "Chirnside Park Primary School - Chirnside Park - 3116",
  "Christ Church Grammar School - South Yarra - 3141",
  "Christ Our Holy Redeemer School - Oakleigh East - 3166",
  "Christ the King Primary School - Braybrook - 3019",
  "Christ the King School - Newcomb - 3219",
  "Christ the Priest Catholic Primary School - Caroline Springs - 3023",
  "Christian College Geelong - Junior School – Belmont - Belmont - 3216",
  "Christian College Geelong - Middle School – Highton - Highton - 3216",
  "Christian College Geelong - Senior School – Waurn Ponds - Waurn Ponds - 3216",
  "Cire Community School - Lilydale - 3140",
  "Cire Community School - Lilydale Campus - Lilydale - 3140",
  "Cire Community School - Mt Evelyn Campus - Mount Evelyn - 3796",
  "Cire Community School Berwick Campus - Berwick - 3806",
  "Clairvaux Catholic School - Belmont - 3216",
  "Clarinda Primary School - Clarinda - 3169",
  "Clayton North Primary School - Clayton - 3168",
  "Clayton South Primary School - Clayton South - 3169",
  "Clifton Hill Primary School - Clifton Hill - 3068",
  "Clonard College - Herne Hill - 3218",
  "Clyde Creek Primary School - Clyde - 3978",
  "Clyde Grammar - Cranbourne - 3977",
  "Clyde Primary School - Clyde - 3978",
  "Clyde Secondary College - Clyde - 3978",
  "Coatesville Primary School - Bentleigh East - 3165",
  "Coburg High School - Coburg - 3058",
  "Coburg High School-Coburg Teaching Unit - Coburg - 3058",
  "Coburg North Primary School - Coburg - 3058",
  "Coburg Primary School - Coburg - 3058",
  "Coburg Special Developmental School - Coburg - 3058",
  "Coburg West Primary School - Coburg - 3058",
  "Coburn Primary School - Melton South - 3338",
  "Cockatoo Primary School - Cockatoo - 3781",
  "Coldstream Primary School - Coldstream - 3770",
  "Collingwood College - Collingwood - 3066",
  "Collingwood College-Collingwood Alternative School - Collingwood - 3066",
  "Collingwood English Language School - Collingwood - 3066",
  "Collingwood English Language School-Broadmeadows Campus - Broadmeadows - 3047",
  "Collingwood English Language School-Craigieburn Campus - Craigieburn - 3064",
  "Concord School - Bundoora - 3083",
  "Concord School-Concord Junior Campus - Watsonia - 3087",
  "Coolaroo South Primary School - Coolaroo - 3048",
  "Copperfield College - Delahey - 3037",
  "Copperfield College-Kings Park Junior Campus - Kings Park - 3021",
  "Copperfield College-Sydenham Junior Campus - Sydenham - 3037",
  "Coral Park Primary School - Hampton Park - 3976",
  "Cornish College - Bangholme - 3175",
  "Corpus Christi School - Glenroy - 3046",
  "Corpus Christi School - Kingsville - 3012",
  "Corpus Christi School - Werribee - 3030",
  "Courtenay Gardens Primary School - Cranbourne North - 3977",
  "Covenant College - Bell Post Hill - 3215",
  "Craigieburn Primary School - Craigieburn - 3064",
  "Craigieburn Secondary College - Craigieburn - 3064",
  "Craigieburn South Primary School - Craigieburn - 3064",
  "Cranbourne Carlisle Primary School - Cranbourne - 3977",
  "Cranbourne East Primary School - Cranbourne East - 3977",
  "Cranbourne East Secondary College - Cranbourne East - 3977",
  "Cranbourne Park Primary School - Cranbourne - 3977",
  "Cranbourne Primary School - Cranbourne - 3977",
  "Cranbourne Secondary College - Cranbourne - 3977",
  "Cranbourne South Primary School - Cranbourne South - 3977",
  "Cranbourne West Primary School - Cranbourne - 3977",
  "Cranbourne West Secondary College - Cranbourne West - 3977",
  "Creekside K-9 College - Caroline Springs - 3023",
  "Crib Point Primary School - Crib Point - 3919",
  "Croxton Special School - Northcote - 3070",
  "Croxton Special School-Transition Learning Centre - Thornbury - 3071",
  "Croydon Community School - Croydon - 3136",
  "Croydon Community School-Capacity Building - Wheelers Hill - 3150",
  "Croydon Community School-OPTIONS@Bayswater - Bayswater - 3153",
  "Croydon Hills Primary School - Croydon Hills - 3136",
  "Croydon Primary School - Croydon - 3136",
  "Croydon Special Developmental School - Croydon South - 3136",
  "Dallas Brooks Community Primary School - Dallas - 3047",
  "Dandenong High School - Dandenong - 3175",
  "Dandenong High School Burremah Grassmere Annexe - Doveton - 3177",
  "Dandenong High School-Cleeland Campus - Dandenong - 3175",
  "Dandenong High School-Myuna Secondary Teaching Unit - Doveton - 3177",
  "Dandenong North Primary School - Dandenong - 3175",
  "Dandenong Primary School - Dandenong - 3175",
  "Dandenong Ranges Steiner School - Narre Warren East - 3782",
  "Dandenong Ranges Steiner School - School Road Campus - Narre Warren East - 3159",
  "Dandenong South Primary School - Dandenong - 3175",
  "Dandenong Valley Special Developmental School - Narre Warren - 3805",
  "Dandenong West Primary School - Dandenong - 3175",
  "Darley Primary School - Darley - 3340",
  "Darul Ulum College of Victoria - Fawkner - 3060",
  "David Scott School - Frankston - 3199",
  "David Scott School - High Street Campus - Frankston - 3199",
  "Davis Creek Primary School - Tarneit - 3029",
  "De La Salle College - Holy Eucharist Campus - Malvern East - 3145",
  "De La Salle College - Kinnoull Campus - Malvern - 3144",
  "De La Salle College - Malvern - 3144",
  "Deanside Primary School - Deanside - 3336",
  "Debney Meadows Primary School - Flemington - 3031",
  "Deepdene Primary School - Deepdene - 3103",
  "Deer Park North Primary School - Deer Park - 3023",
  "Deer Park West Primary School - Deer Park - 3023",
  "Derinya Primary School - Frankston South - 3199",
  "Derrimut Primary School - Derrimut - 3030",
  "Deutsche Schule Melbourne - Fitzroy North - 3068",
  "Devon Meadows Primary School - Devon Meadows - 3977",
  "Diamond Creek East Primary School - Diamond Creek - 3089",
  "Diamond Creek Primary School - Diamond Creek - 3089",
  "Diamond Valley College - Diamond Creek - 3089",
  "Diamond Valley Special Developmental School - Greensborough - 3088",
  "Diggers Rest Primary School - Diggers Rest - 3427",
  "Dingley Primary School - Dingley Village - 3172",
  "Dinjerra Primary School - Braybrook - 3019",
  "Divrei Emineh - Elsternwick - 3185",
  "Djerriwarrh Community & Education Services - Djerriwarrh Community College - Melton - 3337",
  "Docklands Primary School - Docklands - 3008",
  "Dohertys Creek P-9 College - Truganina - 3029",
  "Don Bosco School - Narre Warren - 3805",
  "Donburn Primary School - Doncaster East - 3109",
  "Doncaster Gardens Primary School - Doncaster East - 3109",
  "Doncaster Primary School - Doncaster - 3108",
  "Doncaster Secondary College - Doncaster - 3108",
  "Donvale Christian College - Donvale - 3111",
  "Donvale Christian College - Hall Road Campus - Donvale - 3134",
  "Donvale Primary School - Donvale - 3111",
  "Doreen Primary School - Doreen - 3754",
  "Dorset Primary School - Croydon - 3136",
  "Doveton College - Doveton - 3177",
  "Dromana Primary School - Dromana - 3936",
  "Dromana Secondary College - Dromana - 3936",
  "East Bentleigh Primary School - Bentleigh East - 3165",
  "East Doncaster Secondary College - Doncaster East - 3109",
  "East Preston Islamic College - Preston - 3072",
  "Eastbourne Primary School - Capel Sound - 3939",
  "Eastern Ranges School - Ferntree Gully - 3156",
  "Eastwood Primary School - Ringwood East - 3135",
  "Eastwood Primary School-Eastwood Deaf Facility - Ringwood East - 3135",
  "ECG College Pakenham - Pakenham - 3810",
  "Edenbrook Secondary College - Pakenham - 3810",
  "Edgars Creek Primary School - Wollert - 3750",
  "Edgars Creek Secondary College - Wollert - 3750",
  "Edinburgh College - Lilydale - 3140",
  "Edinburgh College (Primary Campus) - Lilydale - 3140",
  "Edithvale Primary School - Edithvale - 3196",
  "Elevation Secondary College - Craigieburn - 3064",
  "Elisabeth Murdoch College - Langwarrin - 3910",
  "Elsternwick Primary School - Brighton - 3186",
  "Eltham College - King Street Campus - Melbourne - 3000",
  "Eltham College - Lonsdale Street Campus - Melbourne - 3000",
  "Eltham College - Research - 3095",
  "Eltham East Primary School - Eltham - 3095",
  "Eltham High School - Eltham - 3095",
  "Eltham North Primary School - Eltham North - 3095",
  "Eltham Primary School - Eltham - 3095",
  "Elwood College - Elwood - 3184",
  "Elwood Primary School - Elwood - 3184",
  "Emerald Primary School - Emerald - 3782",
  "Emerald Secondary College - Emerald - 3782",
  "Emerson School - Dandenong - 3175",
  "Emerson School-Emerson Middle campus - Dandenong North - 3175",
  "Emmanuel College - Altona North - 3025",
  "Emmanuel College - Notre Dame Campus - Point Cook - 3030",
  "Emmaus Catholic Primary School - Sydenham - 3037",
  "Emmaus College - Burwood Campus - Burwood - 3125",
  "Emmaus College - Vermont South - 3133",
  "Endeavour Hills Specialist School - Endeavour Hills - 3802",
  "Epping Primary School - Epping - 3076",
  "Epping Primary School-Greenbrook Campus - Epping - 3076",
  "Epping Secondary College - Epping - 3076",
  "Epping Views Primary School - Epping - 3076",
  "Erasmus Primary School - Hawthorn - 3122",
  "Essendon Keilor College - Keilor East - 3033",
  "Essendon Keilor College-Niddrie Campus - Niddrie - 3042",
  "Essendon Keilor College-Senior Campus - Essendon - 3040",
  "Essendon North Primary School - Essendon North - 3041",
  "Essendon Primary School - Essendon - 3040",
  "Essex Heights Primary School - Mount Waverley - 3149",
  "Fairfield Primary School - Fairfield - 3078",
  "Fairhills High School - Knoxfield - 3180",
  "Fairhills Primary School - Ferntree Gully - 3156",
  "Fawkner Primary School - Fawkner - 3060",
  "Featherbrook P-9 College - Point Cook - 3030",
  "Fernbrook School - Basin - 3154",
  "Ferntree Gully North Primary School - Ferntree Gully - 3156",
  "Ferny Creek Primary School - Ferny Creek - 3786",
  "Findon Primary School - Mill Park - 3082",
  "Fintona Girls' School - Balwyn - 3103",
  "Firbank Grammar School - Brighton - 3186",
  "Firbank Grammar School - Sandringham Campus - Sandringham - 3191",
  "Firbank Grammar School - Second Campus - Brighton - 3186",
  "Fitra Community School - Clayton South - 3169",
  "Fitzroy Community School - Fitzroy North - 3068",
  "Fitzroy Community School - Thornbury Campus - Thornbury - 3071",
  "Fitzroy High School - Fitzroy North - 3068",
  "Fitzroy North Primary School - Fitzroy North - 3068",
  "Fitzroy Primary School - Fitzroy - 3065",
  "Fleetwood Primary School - Narre Warren - 3805",
  "Flemington Primary School - Flemington - 3031",
  "Flinders Christian Community College - Carrum Downs Campus - Carrum Downs - 3201",
  "Flinders Christian Community College - Tyabb - 3913",
  "Footscray City Primary School - Footscray - 3011",
  "Footscray High School - Barkly Campus - Footscray - 3011",
  "Footscray High School - Footscray - 3011",
  "Footscray High School - Pilgrim Campus - Seddon - 3011",
  "Footscray North Primary School - Footscray - 3011",
  "Footscray Primary School - Footscray - 3011",
  "Footscray West Primary School - West Footscray - 3012",
  "Forest Hill College - Burwood East - 3151",
  "Forest Hill College-Forest Hill Deaf Facility - Burwood East - 3151",
  "Fountain Gate Primary School - Narre Warren - 3805",
  "Fountain Gate Secondary College - Narre Warren - 3805",
  "Frank Dando Sports Academy - Ashwood - 3147",
  "Frankston East Primary School - Frankston - 3199",
  "Frankston Heights Primary School - Frankston - 3199",
  "Frankston High School - Frankston - 3199",
  "Frankston High School-VCE Campus - Frankston - 3199",
  "Frankston Primary School - Frankston - 3199",
  "Frankston Special Developmental School - Frankston - 3199",
  "Furlong Park School For Deaf Children - Sunshine North - 3020",
  "Fyans Park Primary School - Newtown - 3220",
  "Gaayip-Yagila Primary School - Mickleham - 3064",
  "Galilee Regional Catholic Primary School - South Melbourne - 3205",
  "Gardenvale Primary School - Brighton East - 3187",
  "Garrang Wilam Primary School - Truganina - 3029",
  "Geelong Baptist College - Lovely Banks - 3213",
  "Geelong East Primary School - Geelong East - 3219",
  "Geelong Grammar School - Bostock House Campus - Newtown - 3220",
  "Geelong Grammar School - Corio Campus - Corio - 3214",
  "Geelong Grammar School - Toorak campus - Toorak - 3142",
  "Geelong High School - East Geelong - 3219",
  "Geelong Lutheran College - Armstrong Creek - 3217",
  "Geelong South Primary School - South Geelong - 3220",
  "Gembrook Primary School - Gembrook - 3783",
  "Genazzano FCJ College - Kew - 3101",
  "Ghilgai School - Kilsyth - 3137",
  "Giant Steps Melbourne - Kew - 3101",
  "Gilgai Plains Primary School - Kalkallo - 3064",
  "Gilson College - Mernda Campus - Mernda - 3754",
  "Gilson College - Taylors Hill - 3037",
  "Gladesville Primary School - Kilsyth - 3137",
  "Gladstone Park Primary School - Gladstone Park - 3043",
  "Gladstone Park Secondary College - Gladstone Park - 3043",
  "Gladstone Views Primary School - Gladstone Park - 3043",
  "Glen Eira College - Caulfield East - 3145",
  "Glen Eira College-Glen Eira English Language Centre - Caulfield East - 3145",
  "Glen Huntly Primary School - Glen Huntly - 3163",
  "Glen Iris Primary School - Glen Iris - 3146",
  "Glen Katherine Primary School - Eltham North - 3095",
  "Glen Waverley Primary School - Glen Waverley - 3150",
  "Glen Waverley Secondary College - Glen Waverley - 3150",
  "Glen Waverley South Primary School - Glen Waverley - 3150",
  "Glenallen School - Glen Waverley - 3150",
  "Glendal Primary School - Glen Waverley - 3150",
  "Gleneagles Secondary College - Endeavour Hills - 3802",
  "Glenferrie Primary School - Hawthorn - 3122",
  "Glengala Primary School - Sunshine West - 3020",
  "Glenroy Central Primary School - Glenroy - 3046",
  "Glenroy Private - Glenroy - 3046",
  "Glenroy Secondary College - Glenroy - 3046",
  "Glenroy Specialist School - Glenroy - 3046",
  "Glenroy West Primary School - Glenroy - 3046",
  "Glowrey Catholic Primary School - Wollert - 3750",
  "Good News Lutheran College - Tarneit - 3029",
  "Good Samaritan Catholic Primary School - Roxburgh Park - 3064",
  "Good Shepherd Lutheran Primary School - Croydon Hills - 3136",
  "Good Shepherd School - Wheelers Hill - 3150",
  "Goonawarra Primary School - Sunbury - 3429",
  "Grayling Primary School - Clyde North - 3978",
  "Great Ryrie Primary School - Heathmont - 3135",
  "Greenhills Primary School - Greensborough - 3088",
  "Greensborough Primary School - Greensborough - 3088",
  "Greensborough Secondary College - Greensborough - 3088",
  "Greenvale Primary School - Greenvale - 3059",
  "Greenvale Secondary College - Greenvale - 3059",
  "Greythorn Primary School - Balwyn North - 3104",
  "Grovedale College - Grovedale - 3216",
  "Grovedale Primary School - Grovedale - 3216",
  "Grovedale West Primary School - Grovedale - 3216",
  "Grovedale West Primary School-Grovedale West Deaf Facility - Grovedale - 3216",
  "Haileybury College - Berwick Campus - Berwick - 3806",
  "Haileybury College - Brighton Campus - Brighton - 3186",
  "Haileybury College - City Campus - West Melbourne - 3006",
  "Haileybury College - Keysborough - 3173",
  "Haileybury Girls College - Berwick Campus - Berwick - 3806",
  "Haileybury Girls College - Brighton Campus - Brighton - 3186",
  "Haileybury Girls College - City Campus - West Melbourne - 3006",
  "Haileybury Girls College - Keysborough - 3173",
  "Hallam Primary School - Hallam - 3803",
  "Hallam Senior Secondary College - Hallam - 3803",
  "Hallam Senior Secondary College-Hallam Senior College / Mission Australia Annex - Doveton - 3177",
  "Hamlyn Banks Primary School - Hamlyn Heights - 3215",
  "Hamlyn Views School - Hamlyn Heights - 3215",
  "Hampton Park Primary School - Hampton Park - 3976",
  "Hampton Park Secondary College - Hampton Park - 3976",
  "Hampton Primary School - Hampton - 3188",
  "Harkaway Hills College - Narre Warren North - 3804",
  "Harkaway Primary School - Harkaway - 3806",
  "Harrisfield Primary School - Noble Park - 3174",
  "Hartwell Primary School - Camberwell - 3124",
  "Harvest Home Primary School - Epping - 3076",
  "Hastings Primary School - Hastings - 3915",
  "Hawthorn West Primary School - Hawthorn - 3122",
  "Hazel Glen College - Doreen - 3754",
  "Heany Park Primary School - Rowville - 3178",
  "Heathdale Christian College - Melton Campus - Kurunjang - 3337",
  "Heathdale Christian College - Werribee - 3030",
  "Heatherhill Primary School - Springvale - 3171",
  "Heatherton Christian College - Clarinda - 3169",
  "Heatherwood School - Donvale - 3111",
  "Heatherwood School-State Vision Resource Centre - Donvale - 3111",
  "Heathmont College - Heathmont - 3135",
  "Heathmont East Primary School - Heathmont - 3135",
  "Heidelberg Primary School - Heidelberg - 3084",
  "Heritage College - Narre Warren South - 3805",
  "Heritage College - Officer Campus - Officer - 3809",
  "Heritage College Knox - Main Campus - The Basin - 3156",
  "Herne Hill Primary School - Hamlyn Heights - 3215",
  "Hester Hornbrook Academy - Melbourne - 3000",
  "Hester Hornbrook Academy - Prahran Campus - Prahan - 3181",
  "Hester Hornbrook Academy - Sunshine Campus - Sunshine - 3020",
  "Highton Primary School - Highton - 3216",
  "Highvale Primary School - Glen Waverley - 3150",
  "Highvale Secondary College - Glen Waverley - 3150",
  "Hillcrest Christian College - Clyde North - 3978",
  "Hillsmeade Primary School - Narre Warren South - 3805",
  "Hoa Nghiem Primary School - Springvale South - 3172",
  "Holmes Grammar School - Melbourne - 3000",
  "Holy Child School - Dallas - 3047",
  "Holy Cross Catholic Primary School - Mickleham - 3064",
  "Holy Eucharist School - St Albans South - 3021",
  "Holy Family School - Bell Park - 3215",
  "Holy Family School - Doveton - 3177",
  "Holy Family School - Mount Waverley - 3149",
  "Holy Name School - Reservoir - 3073",
  "Holy Rosary School - Kensington - 3031",
  "Holy Saviour Parish School - Vermont South - 3133",
  "Holy Spirit Parish School - Manifold Heights - 3218",
  "Holy Spirit School - Ringwood North - 3134",
  "Holy Spirit School - Thornbury - 3071",
  "Holy Trinity Catholic Primary School - Sunbury - 3429",
  "Holy Trinity Primary School - Eltham North - 3095",
  "Holy Trinity School - Wantirna South - 3152",
  "Homestead Senior Secondary College - Point Cook - 3030",
  "Hoppers Crossing Secondary College - Hoppers Crossing - 3029",
  "Hughesdale Primary School - Hughesdale - 3166",
  "Hume Anglican Grammar - Donnybrook Campus - Donnybrook - 3064",
  "Hume Anglican Grammar - Mickleham - 3064",
  "Hume Central Secondary College - Broadmeadows - 3047",
  "Hume Central Secondary College-Blair Street Campus - Broadmeadows - 3047",
  "Hume Central Secondary College-Dimboola Road Campus - Broadmeadows - 3047",
  "Hume Central Secondary College-Hume Central English Language Campus - Broadmeadows - 3047",
  "Hume Valley School - Broadmeadows - 3047",
  "Hume Valley School-Narrun Campus - Dallas - 3047",
  "Hume Valley School-Tanderrum Way Campus - Broadmeadows - 3047",
  "Huntingdale Primary School - Oakleigh South - 3167",
  "Huntingtower School - Mount Waverley - 3149",
  "Hurstbridge Primary School - Hurstbridge - 3099",
  "Ignatius Learning Centre - Richmond - 3121",
  "Ilim College - Dallas - 3047",
  "Ilim College - Doveton Campus - Doveton - 3177",
  "Ilim College - Glenroy Campus - Glenroy - 3046",
  "Ilim College - Kiewa Campus - Dallas - 3047",
  "Indie School (Bacchus Marsh) - Bacchus Marsh - 3340",
  "Indie School Wodonga - Indie School Ringwood Campus - Ringwood - 3134",
  "Iona College Geelong - Charlemont - 3217",
  "Iramoo Primary School - Wyndham Vale - 3024",
  "Islamic College Of Melbourne - Tarneit - 3029",
  "Ivanhoe East Primary School - Ivanhoe East - 3079",
  "Ivanhoe East Primary School-Wilfred Road Campus - Ivanhoe East - 3079",
  "Ivanhoe Girls' Grammar School - Ivanhoe - 3079",
  "Ivanhoe Grammar School - Ivanhoe - 3079",
  "Ivanhoe Grammar School - Plenty Campus - Mernda - 3754",
  "Ivanhoe Grammar School - University Campus - Macleod - 3085",
  "Ivanhoe Primary School - Ivanhoe - 3079",
  "Jacana School for Autism - Jacana - 3047",
  "Jackson School - St Albans - 3021",
  "James Cook Primary School - Endeavour Hills - 3802",
  "Japanese School of Melbourne - Caulfield South - 3162",
  "Jells Park Primary School - Wheelers Hill - 3150",
  "Jennings Street School - Laverton - 3028",
  "John Fawkner Secondary College - Fawkner - 3060",
  "John Fawkner Secondary College-Sports Learning Centre - Fawkner - 3060",
  "John Henry Primary School - Pakenham - 3810",
  "John Monash Science School - Clayton - 3168",
  "John Paul College - Frankston - 3199",
  "Kalinda Primary School - Ringwood - 3134",
  "Kallista Primary School - Kallista - 3791",
  "Kamaruka - Primary Campus - South Yarra - 3141",
  "Kamaruka - South Yarra - 3141",
  "Kambrya College - Berwick - 3806",
  "Kananook Primary School - Seaford - 3198",
  "Kangaroo Ground Primary School - Kangaroo Ground - 3097",
  "Kardinia International College - Bell Post Hill - 3215",
  "Karingal Heights Primary School - Frankston - 3199",
  "Karingal Primary School - Frankston - 3199",
  "Karoo Primary School - Rowville - 3178",
  "Katandra School - Ormond - 3204",
  "Keelonith Primary School - Greenvale - 3059",
  "Keilor Downs Secondary College - Keilor Downs - 3038",
  "Keilor Heights Primary School - Keilor East - 3033",
  "Keilor Primary School - Keilor - 3036",
  "Keilor Views Primary School - Keilor Downs - 3038",
  "Kensington Community High School - Kensington - 3031",
  "Kensington Primary School - Kensington - 3031",
  "Kent Park Primary School - Ferntree Gully - 3156",
  "Kerrimuir Primary School - Box Hill North - 3129",
  "Kew East Primary School - Kew East - 3102",
  "Kew High School - Kew East - 3102",
  "Kew Primary School - Kew - 3101",
  "Keysborough Gardens Primary School - Keysborough - 3173",
  "Keysborough Primary School - Springvale South - 3172",
  "Keysborough Secondary College - Springvale South - 3172",
  "Keysborough Secondary College-Acacia Campus - Keysborough - 3173",
  "Kilberry Valley Primary School - Hampton Park - 3976",
  "Kilbreda College - Mentone - 3194",
  "Killara Primary School - Sunbury - 3429",
  "Killester College - Springvale - 3171",
  "Kilsyth Primary School - Kilsyth - 3137",
  "Kilvington Grammar School - Ormond - 3204",
  "Kings Park Primary School - St Albans - 3021",
  "Kingsbury Primary School - Kingsbury - 3083",
  "Kingsley Park Primary School - Frankston - 3199",
  "Kingston Heath Primary School - Cheltenham - 3192",
  "Kingsville Primary School - Yarraville - 3013",
  "Kingswood College - Box Hill - 3128",
  "Kingswood Primary School - Dingley Village - 3172",
  "Kismet Park Primary School - Sunbury - 3429",
  "Knox Central Primary School - Boronia - 3155",
  "Knox Gardens Primary School - Wantirna South - 3152",
  "Knox Park Primary School - Knoxfield - 3180",
  "Kolbe Catholic College - Greenvale - 3059",
  "Koonung Secondary College - Mont Albert North - 3129",
  "Kororoit Creek Primary School - Burnside Heights - 3023",
  "Korowa Anglican Girls' School - Glen Iris - 3146",
  "Kunyung Primary School - Mount Eliza - 3930",
  "Kurunjang Primary School - Melton - 3337",
  "Kurunjang Secondary College - Melton - 3337",
  "Laburnum Primary School - Blackburn - 3130",
  "Lakeside College - Pakenham - 3810",
  "Lakeview Senior College - Caroline Springs - 3023",
  "Lalor East Primary School - Thomastown - 3074",
  "Lalor Gardens Primary School - Lalor - 3075",
  "Lalor North Primary School - Lalor - 3075",
  "Lalor North Secondary College - Epping - 3076",
  "Lalor Primary School - Lalor - 3075",
  "Lalor Secondary College - Lalor - 3075",
  "Langwarrin Park Primary School - Langwarrin - 3910",
  "Langwarrin Primary School - Langwarrin - 3910",
  "Lara Lake Primary School - Lara Lake - 3212",
  "Lara Primary School - Lara - 3212",
  "Lara Secondary College - Lara - 3212",
  "Laurimar Primary School - Doreen - 3754",
  "Lauriston Girls' School - Armadale - 3143",
  "Lauriston Girls' School - Blairholme Campus - Armadale - 3143",
  "Laverton P-12 College - Laverton - 3028",
  "Le Page Primary School - Cheltenham - 3192",
  "Learning Co-Operative School - Hurstbridge - 3099",
  "Leibler Yavneh College - Elsternwick - 3185",
  "Leopold Primary School - Leopold - 3224",
  "Lighthouse Christian College - Keysborough - 3173",
  "Lighthouse Christian College Cranbourne - Cranbourne - 3977",
  "Lilydale Heights College - Lilydale - 3140",
  "Lilydale High School - Lilydale - 3140",
  "Lilydale Primary School - Lilydale - 3140",
  "Livingstone Primary School - Vermont South - 3133",
  "Lloyd Street Primary School - Malvern East - 3145",
  "Loreto Mandeville Hall - Toorak - 3142",
  "Lower Plenty Primary School - Lower Plenty - 3093",
  "Lowther Hall Anglican Grammar School - Essendon - 3040",
  "Loyola College - Watsonia - 3087",
  "Lumen Christi School - Point Cook - 3030",
  "Luther College - Croydon - 3136",
  "Lynall Hall Community School - Richmond - 3121",
  "Lynall Hall Community School-Richmond Campus - Richmond - 3121",
  "Lynall Hall Community School-The Island Campus - Coburg - 3058",
  "Lynbrook Primary School - Lynbrook - 3975",
  "Lyndale Greens Primary School - Dandenong North - 3175",
  "Lyndale Secondary College - Dandenong North - 3175",
  "Lyndhurst Primary School - Lyndhurst - 3975",
  "Lyndhurst Secondary College - Cranbourne - 3977",
  "Lyrebird College - Coldstream - 3770",
  "Lysterfield Lake College - Narre Warren North - 3804",
  "Lysterfield Primary School - Lysterfield - 3156",
  "Macclesfield Primary School - Macclesfield - 3782",
  "Mackellar Primary School - Delahey - 3037",
  "MacKillop Catholic Regional College - Werribee - 3030",
  "MacKillop Specialist School - Flexible Learning Centre Maidstone - Maidstone - 3012",
  "MacKillop Specialist School - MacKillop Education Caulfield - Caulfield - 3161",
  "MacKillop Specialist School - Whittington - 3219",
  "Macleod College - Macleod - 3085",
  "MacRobertson Girls High School - Melbourne - 3004",
  "Maharishi School of the Age of Enlightenment - Reservoir - 3073",
  "Mahogany Rise Primary School - Frankston North - 3200",
  "Mahogany Rise Primary School-Mahogany Rise Student Development Centre - Frankston North - 3200",
  "Malvern Central School - Malvern - 3144",
  "Malvern Primary School - Malvern East - 3145",
  "Malvern Valley Primary School - Malvern East - 3145",
  "Manchester Primary School - Mooroolbark - 3138",
  "Mandama Primary School - Grovedale - 3216",
  "Manifold Heights Primary School - Manifold Heights - 3218",
  "Manor Lakes P-12 College - Wyndham Vale - 3024",
  "Manorvale Primary School - Werribee - 3030",
  "Maramba Primary School - Narre Warren - 3805",
  "Maranatha Christian School - Endeavour Hills - 3802",
  "Maranatha Christian School - Officer Campus - Officer - 3809",
  "Marcellin College - Bulleen - 3105",
  "Marian College - Sunshine West - 3020",
  "Maribyrnong Secondary College - Maribyrnong - 3032",
  "Marlborough Primary School - Heathmont - 3135",
  "Marnebek School Cranbourne - Cranbourne East - 3977",
  "Marnebek School Cranbourne-Cranbourne East Campus - Cranbourne East - 3977",
  "Mary Immaculate School - Ivanhoe - 3079",
  "Mary MacKillop School - Narre Warren North - 3804",
  "Marymede Catholic College - South Morang - 3752",
  "Mater Christi College - Belgrave - 3160",
  "Matthew Flinders Girls Secondary College - Geelong - 3220",
  "Mazenod College - Mulgrave - 3170",
  "McClelland Secondary College - Frankston - 3199",
  "Mckinnon Primary School - Ormond - 3204",
  "Mckinnon Secondary College - Mckinnon - 3204",
  "Meadow Heights Primary School - Meadow Heights - 3048",
  "Meadowglen Primary School - Epping - 3076",
  "Meadows Primary School - Broadmeadows - 3047",
  "Melba Secondary College - Croydon - 3136",
  "Melbourne Girls College - Richmond - 3121",
  "Melbourne Girls Grammar - Morris Hall Campus - South Yarra - 3141",
  "Melbourne Girls Grammar - South Yarra - 3141",
  "Melbourne Grammar School - Grimwade Campus - Caulfield North - 3161",
  "Melbourne Grammar School - Melbourne - 3004",
  "Melbourne Grammar School - Wadhurst Campus - Melbourne - 3004",
  "Melbourne High School - South Yarra - 3141",
  "Melbourne Indigenous Transition School - Richmond - 3121",
  "Melbourne Montessori School - Brighton East Campus - Brighton East - 3187",
  "Melbourne Montessori School - Caulfield South - 3162",
  "Melbourne Montessori School - Grange Road Campus - Caulfield East - 3145",
  "Melbourne Rudolf Steiner School - Warranwood - 3134",
  "Melton Christian College - Brookfield - 3338",
  "Melton Primary School - Melton - 3337",
  "Melton Secondary College - Melton - 3337",
  "Melton Secondary College-CaLM  Link up Campus - Kurunjang - 3338",
  "Melton South Primary School - Melton South - 3338",
  "Melton Specialist School - Melton - 3337",
  "Melton West Primary School - Melton West - 3337",
  "Mentone Girls' Grammar School - Mentone - 3194",
  "Mentone Girls Secondary College - Mentone - 3194",
  "Mentone Grammar School - Mentone - 3194",
  "Mentone Park Primary School - Mentone - 3194",
  "Mentone Primary School - Mentone - 3194",
  "Menzies Creek Primary School - Menzies Creek - 3159",
  "Mercy College - Coburg North - 3058",
  "Mernda Central P-12 College - Mernda - 3754",
  "Mernda Park Primary School - Mernda - 3754",
  "Mernda Primary School - Mernda - 3754",
  "Merri Creek Primary School - Fitzroy North - 3068",
  "Merriang Special Developmental School - Lalor - 3075",
  "Merriang Special Developmental School-Junior Campus - South Morang - 3752",
  "Methodist Ladies' College - Kew - 3101",
  "Mickleham Primary School - Mickleham - 3064",
  "Middle Park Primary School - Middle Park - 3206",
  "Milgate Primary School - Doncaster East - 3109",
  "Mill Park Heights Primary School - Mill Park - 3082",
  "Mill Park Primary School - Mill Park - 3082",
  "Mill Park Secondary College - Mill Park - 3082",
  "Mill Park Secondary College-Senior Campus - Epping - 3076",
  "Minaret College - Doveton Campus - Springvale - 3177",
  "Minaret College - Officer Campus - Officer - 3809",
  "Minaret College - Springvale - 3171",
  "Mirripoa Primary School - Mount Duneed - 3217",
  "Mitcham Primary School - Mitcham - 3132",
  "Monash Special Developmental School - Wheelers Hill - 3150",
  "Monbulk College - Monbulk - 3793",
  "Monbulk Primary School - Monbulk - 3793",
  "Monmia Primary School - Keilor Downs - 3038",
  "Mont Albert Primary School - Mont Albert - 3127",
  "Montague Continuing Education Centre - South Melbourne - 3205",
  "Monterey Secondary College - Frankston North - 3200",
  "Montmorency Primary School - Montmorency - 3094",
  "Montmorency Secondary College - Montmorency - 3094",
  "Montmorency South Primary School - Montmorency - 3094",
  "Montpellier Primary School - Highton - 3216",
  "Montrose Primary School - Montrose - 3765",
  "Moolap Primary School - Moolap - 3224",
  "Moomba Park Primary School - Fawkner - 3060",
  "Moonee Ponds Primary School - Moonee Ponds - 3039",
  "Moonee Ponds West Primary School - Moonee Ponds - 3039",
  "Moorabbin Primary School - Moorabbin - 3189",
  "Moorooduc Primary School - Moorooduc - 3933",
  "Mooroolbark College - Mooroolbark - 3138",
  "Mooroolbark East Primary School - Mooroolbark - 3138",
  "Mooroolbark Grammar - Mooroolbark - 3138",
  "Morang South Primary School - South Morang - 3752",
  "Mordialloc Beach Primary School - Mordialloc - 3195",
  "Mordialloc College - Mordialloc - 3195",
  "Moreland Primary School - Coburg - 3058",
  "Mornington Park Primary School - Mornington - 3931",
  "Mornington Primary School - Mornington - 3931",
  "Mornington Secondary College - Mornington - 3931",
  "Mornington Special Developmental School - Mornington - 3931",
  "Mossfiel Primary School - Hoppers Crossing - 3029",
  "Mossgiel Park Primary School - Endeavour Hills - 3802",
  "Mother of God School - Ardeer - 3022",
  "Mother Teresa School - Craigieburn - 3064",
  "Mount Alexander 7-12 College - Flemington - 3031",
  "Mount Alexander 7-12 College-River Nile Campus - North Melbourne - 3051",
  "Mount Dandenong Primary School - Mount Dandenong - 3767",
  "Mount Duneed Regional Primary School - Mount Duneed - 3217",
  "Mount Eliza North Primary School - Mount Eliza - 3930",
  "Mount Eliza Primary School - Mount Eliza - 3930",
  "Mount Eliza Secondary College - Mount Eliza - 3930",
  "Mount Erin Secondary College - Frankston South - 3199",
  "Mount Erin Secondary College-Mount Erin Deaf Facility - Frankston - 3199",
  "Mount Evelyn Christian School - Mount Evelyn - 3796",
  "Mount Evelyn Christian School - Ranges Tec Campus - Lilydale - 3140",
  "Mount Evelyn Primary School - Mount Evelyn - 3796",
  "Mount Lilydale Mercy College - Lilydale - 3140",
  "Mount Martha Primary School - Mount Martha - 3934",
  "Mount Pleasant Road Nunawading Primary School - Nunawading - 3131",
  "Mount Ridley P-12 College - Craigieburn - 3064",
  "Mount Scopus Memorial College - Burwood - 3125",
  "Mount Scopus Memorial College - Fink Karp Ivany Campus - Caulfield South - 3162",
  "Mount Scopus Memorial College - Gandel Besen House Campus - St Kilda East - 3183",
  "Mount St Joseph Girls' College - Altona - 3018",
  "Mount View Primary School - Glen Waverley - 3150",
  "Mount View Primary School-Mount View Deaf Facility - Glen Waverley - 3150",
  "Mount Waverley Heights Primary School - Mount Waverley - 3149",
  "Mount Waverley North Primary School - Mount Waverley - 3149",
  "Mount Waverley Primary School - Mount Waverley - 3149",
  "Mount Waverley Secondary College - Mount Waverley - 3149",
  "Mount Waverley Secondary College-Junior Campus - Mount Waverley - 3149",
  "Mountain District Christian School - Monbulk - 3793",
  "Mountain District Community College - Ferntree Gully - 3156",
  "Mountain Gate Primary School - Ferntree Gully - 3156",
  "Movelle Primary School - Kings Park - 3021",
  "Mt Hira College - Keysborough - 3173",
  "Muhammadiyah Australia College - Melton - 3337",
  "Mulgrave Primary School - Mulgrave - 3170",
  "Mullauna Secondary College - Mitcham - 3132",
  "Mullum Primary School - Ringwood - 3134",
  "Murrumbeena Primary School - Murrumbeena - 3163",
  "My College - Dallas - 3047",
  "Naranga Special School - Frankston - 3199",
  "Narre Warren North Primary School - Narre Warren North - 3804",
  "Narre Warren South P-12 College - Narre Warren South - 3805",
  "Nazareth College - Waverley Gardens - 3174",
  "Nazareth School - Grovedale - 3216",
  "Nelson Park School - Bell Park - 3215",
  "Nelson Park School-Illinois Avenue Annexe - Corio - 3214",
  "Nepean Special School - Seaford - 3198",
  "Newbury Primary School - Craigieburn - 3064",
  "Newcomb Primary School - Newcomb - 3219",
  "Newcomb Secondary College - Newcomb - 3219",
  "Newcomb Secondary College-Victorian Sailing Water Safety School - Geelong - 3220",
  "Newlands Primary School - Preston - 3072",
  "Newmark Primary - Williamstown - 3016",
  "Newport Gardens Primary School - Newport - 3015",
  "Newport Lakes Primary School - Newport - 3015",
  "Newtown Primary School - Newtown - 3220",
  "Niddrie Autistic School - Niddrie - 3042",
  "Niddrie Primary School - Niddrie - 3042",
  "Noble Park English Language School - Noble Park - 3174",
  "Noble Park English Language School-Casey Campus - Hampton Park - 3976",
  "Noble Park English Language School-Springvale Campus - Springvale - 3171",
  "Noble Park English Language School-Stonnington Glen Eira Campus - Glen Huntly - 3163",
  "Noble Park Primary School - Noble Park - 3174",
  "Noble Park Secondary College - Noble Park - 3174",
  "Norris Bank Primary School - Bundoora - 3083",
  "North Geelong Secondary College - North Geelong - 3215",
  "North Melbourne Primary School - North Melbourne - 3051",
  "Northcote High School - Northcote - 3070",
  "Northcote Primary School - Northcote - 3070",
  "North-Eastern Montessori School - Plenty Valley International Montessori School - St Helena - 3088",
  "Northern Bay P-12 College - Corio - 3214",
  "Northern Bay P-12 College-Hendy Street P-8 Campus - Corio - 3214",
  "Northern Bay P-12 College-Peacock Avenue P-8 Campus - Norlane - 3214",
  "Northern Bay P-12 College-Tallis Street P-8 Campus - Norlane - 3214",
  "Northern Bay P-12 College-Wexford Court P-8 Campus - Corio - 3214",
  "Northern College of the Arts and Technology - Preston - 3072",
  "Northern School For Autism - Reservoir - 3073",
  "Northern School For Autism-Lalor Campus - Lalor - 3075",
  "Northside Christian College - Bundoora - 3083",
  "Norwood Secondary College - Ringwood - 3134",
  "Nossal High School - Berwick - 3806",
  "Nunawading Christian College - Primary - Nunawading - 3131",
  "Nunawading Christian College - Secondary - Nunawading - 3131",
  "Oak Park Primary School - Oak Park - 3046",
  "Oakleigh Grammar - Oakleigh - 3166",
  "Oakleigh Primary School - Oakleigh - 3166",
  "Oakleigh South Primary School - Oakleigh South - 3167",
  "Oakwood School - Caulfield North - 3161",
  "Oakwood School-Capel Sound Campus - Capel Sound - 3940",
  "Oakwood School-Career Pathway Centre - Frankston - 3199",
  "Oakwood School-Frankston Campus - Frankston - 3199",
  "Oakwood School-Hastings Campus - Hastings - 3915",
  "Oakwood School-Mornington Campus - Mornington - 3931",
  "Oakwood School-Noble Park Campus - Noble Park North - 3174",
  "Oakwood School-Oakwood School VCAL Campus - Chelsea - 3196",
  "Oakwood School-Pakenham Campus - Pakenham - 3810",
  "Oatlands Primary School - Narre Warren - 3805",
  "Oberon High School - Armstrong Creek - 3217",
  "Oberon Primary School - Belmont - 3216",
  "Officer Primary School - Officer - 3809",
  "Officer Secondary College - Officer - 3809",
  "Officer Specialist School - Officer - 3809",
  "Old Orchard Primary School - Blackburn North - 3130",
  "Olinda Primary School - Olinda - 3788",
  "OneSchool Global Vic - Berwick Centre - Officer - 3809",
  "OneSchool Global Vic - Melton Centre - Melton West - 3337",
  "OneSchool Global Vic - Melton West - 3337",
  "Orchard Grove Primary School - Blackburn South - 3130",
  "Orchard Park Primary School - Officer - 3809",
  "Ormond Primary School - Ormond - 3204",
  "Osborne Primary School - Mount Martha - 3934",
  "Oscar Romero Catholic Primary School - Craigieburn - 3064",
  "Our Holy Redeemer School - Surrey Hills - 3127",
  "Our Lady Help of Christians School - Brunswick East - 3057",
  "Our Lady Help of Christians School - Eltham - 3095",
  "Our Lady of Fatima School - Rosebud - 3939",
  "Our Lady of Good Counsel School - Deepdene - 3103",
  "Our Lady of Lourdes School - Bayswater - 3153",
  "Our Lady of Lourdes School - Prahran - 3181",
  "Our Lady of Mercy College - Heidelberg - 3084",
  "Our Lady of Mount Carmel School - Sunbury - 3429",
  "Our Lady of Perpetual Help School - Ringwood - 3134",
  "Our Lady of Perpetual Succour School - Surrey Hills - 3127",
  "Our Lady of Sion College - Box Hill - 3128",
  "Our Lady of the Assumption School - Cheltenham - 3192",
  "Our Lady of the Immaculate Conception School - Sunshine - 3020",
  "Our Lady of the Nativity School - Aberfeldie - 3040",
  "Our Lady of the Pines School - Donvale - 3111",
  "Our Lady of the Sacred Heart College - Bentleigh - 3204",
  "Our Lady of the Southern Cross - Wyndham Vale - 3024",
  "Our Lady of the Way School - Kingsbury - 3083",
  "Our Lady's School - Craigieburn - 3064",
  "Overnewton Anglican Community College - Keilor - 3036",
  "Overnewton Anglican Community College - Taylors Lakes Campus - Taylors Lakes - 3038",
  "Overport Primary School - Frankston - 3199",
  "Oxley Christian College - Chirnside Park - 3116",
  "Ozford College - Melbourne - 3000",
  "Ozford College - Ozford College Campus - Melbourne - 3000",
  "Padua College - Mornington - 3931",
  "Padua College - Rosebud Campus - Rosebud - 3939",
  "Padua College - Tyabb campus - Tyabb - 3913",
  "Pakenham Consolidated School - Pakenham - 3810",
  "Pakenham Hills Primary School - Pakenham - 3810",
  "Pakenham Lakeside Primary School - Pakenham - 3810",
  "Pakenham Primary School - Pakenham - 3810",
  "Pakenham Secondary College - Pakenham - 3810",
  "Pakenham Springs Primary School - Pakenham - 3810",
  "Panton Hill Primary School - Panton Hill - 3759",
  "Parade College - Bundoora - 3083",
  "Parade College - Preston Campus - Preston - 3072",
  "Park Orchards Primary School - Park Orchards - 3114",
  "Park Ridge Primary School - Rowville - 3178",
  "Parkdale Primary School - Parkdale - 3195",
  "Parkdale Secondary College - Mordialloc - 3195",
  "Parkhill Primary School - Ashwood - 3147",
  "Parkmore Primary School - Forest Hill - 3131",
  "Parktone Primary School - Parkdale - 3195",
  "Parkville College - Parkville - 3052",
  "Parkville College-Ascot Vale Secure Welfare Campus - Ascot Vale - 3032",
  "Parkville College-Maribyrnong Secure Welfare Campus - Maribyrnong - 3032",
  "Parkwood Green Primary School - Hillside - 3037",
  "Pascoe Vale Girls Secondary College - Pascoe Vale - 3044",
  "Pascoe Vale North Primary School - Pascoe Vale - 3044",
  "Pascoe Vale Primary School - Pascoe Vale - 3044",
  "Pascoe Vale South Primary School - Pascoe Vale South - 3044",
  "Patterson Lakes Primary School - Patterson Lakes - 3197",
  "Patterson River Secondary College - Seaford - 3198",
  "Pearcedale Primary School - Pearcedale - 3912",
  "Pearcedale Primary School-Pearcedale Deaf Facility - Pearcedale - 3912",
  "Pembroke Primary School - Mooroolbark - 3138",
  "Penders Grove Primary School - Thornbury - 3071",
  "Peninsula Grammar - Mount Eliza - 3930",
  "Peninsula Specialist College - Dromana - 3936",
  "Penleigh & Essendon Grammar School - Essendon Campus - Essendon - 3040",
  "Penleigh & Essendon Grammar School - Keilor East - 3033",
  "Penleigh & Essendon Grammar School - Moonee Ponds Campus - Moonee Ponds - 3039",
  "Penola Catholic College - Broadmeadows - 3047",
  "Penola Catholic College - Glenroy Campus - Glenroy - 3046",
  "Pentland Primary School - Bacchus Marsh - 3340",
  "Peter Lalor Secondary College - Lalor - 3075",
  "Pinewood Primary School - Mount Waverley - 3149",
  "Plenty Parklands Primary School - Mill Park - 3082",
  "Plenty River College - South Morang - 3752",
  "Plenty Valley Christian College - Doreen - 3754",
  "Point Cook Prep - Year 9 College - Point Cook - 3030",
  "Point Cook Senior Secondary College - Point Cook - 3030",
  "Port Melbourne Primary School - Port Melbourne - 3207",
  "Port Melbourne Secondary College - Port Melbourne - 3207",
  "Port Phillip Specialist School - Port Melbourne - 3207",
  "Prahran High School - Windsor - 3181",
  "Presbyterian Ladies' College - Burwood - 3125",
  "Preshil, The Margaret Lyttle Memorial School - Blackhall-Kalimna Preshil Senior School - Kew - 3101",
  "Preshil, The Margaret Lyttle Memorial School - Kew - 3101",
  "Preston High School - Preston - 3072",
  "Preston North East Primary School - East Preston - 3072",
  "Preston Primary School - Preston - 3072",
  "Preston Reservoir Adult Community Education Inc | PRACE College - Mernda Campus - Reservoir - 3754",
  "Preston Reservoir Adult Community Education Inc | PRACE College - Reservoir - 3073",
  "Preston South Primary School - Preston - 3072",
  "Preston West Primary School - Preston - 3072",
  "Princes Hill Primary School - Carlton North - 3054",
  "Princes Hill Secondary College - Princes Hill - 3054",
  "Queen of Peace Primary School - Altona Meadows - 3028",
  "Ramlegh Park Primary School - Clyde North - 3978",
  "Rangebank Primary School - Cranbourne - 3977",
  "Rangeview Primary School - Mitcham - 3132",
  "Regency Park Primary School - Wantirna - 3152",
  "Research Primary School - Research - 3095",
  "Reservoir East Primary School - Reservoir - 3073",
  "Reservoir High School - Reservoir - 3073",
  "Reservoir High School-Heidelberg Secondary Teaching Unit - Reservoir - 3073",
  "Reservoir Primary School - Reservoir - 3073",
  "Reservoir Views Primary School - Reservoir - 3073",
  "Reservoir West Primary School - Reservoir - 3073",
  "Resurrection House - Essendon - 3040",
  "Resurrection School - Keysborough - 3173",
  "Resurrection School - Kings Park - 3021",
  "Richmond High School - Richmond - 3121",
  "Richmond High School-Gleadell Street Campus - Richmond - 3121",
  "Richmond Primary School - Richmond - 3121",
  "Richmond West Primary School - Richmond - 3121",
  "Ringwood Heights Primary School - Ringwood North - 3134",
  "Ringwood North Primary School - Ringwood North - 3134",
  "Ringwood Secondary College - Ringwood - 3134",
  "Ripponlea Primary School - St Kilda East - 3183",
  "River Gum Primary School - Hampton Park - 3976",
  "River Nile School - North Melbourne - 3051",
  "Riverbend Primary School - Wyndham Vale - 3024",
  "Rivercrest Christian College - Clyde North - 3978",
  "Roberts McCubbin Primary School - Box Hill South - 3128",
  "Rockbank Primary School - Rockbank - 3335",
  "Rolling Hills Primary School - Mooroolbark - 3138",
  "Rollins Primary School - Bell Post Hill - 3215",
  "Rosamond Special School - Braybrook - 3019",
  "Rosamond Special School Olympia Street Campus - Tottenham - 3012",
  "Rosanna Golf Links Primary School - Rosanna - 3084",
  "Rosanna Golf Links Primary School-Rosanna Golf Links Deaf Facility - Rosanna - 3084",
  "Rosanna Primary School - Rosanna - 3084",
  "Rosebud Primary School - Rosebud - 3939",
  "Rosebud Secondary College - Rosebud - 3939",
  "Rosehill Secondary College - Niddrie - 3042",
  "Rosewood Downs Primary School - Dandenong North - 3175",
  "Roslyn Primary School - Belmont - 3216",
  "Rossbourne School - Hawthorn - 3122",
  "Rowellyn Park Primary School - Carrum Downs - 3201",
  "Rowville Primary School - Rowville - 3178",
  "Rowville Secondary College - Rowville - 3178",
  "Rowville Secondary College-Eastern Campus - Rowville - 3178",
  "Roxburgh College - Roxburgh Park - 3064",
  "Roxburgh College-The Gateway School - Broadmeadows - 3047",
  "Roxburgh Homestead Primary School - Roxburgh Park - 3064",
  "Roxburgh Park Primary School - Roxburgh Park - 3064",
  "Roxburgh Rise Primary School - Roxburgh Park - 3064",
  "Royal Childrens Hospital Education Institute - Parkville - 3052",
  "Ruskin Park Primary School - Croydon - 3136",
  "Ruyton Girls' School - Kew - 3101",
  "Rye Primary School - Rye - 3941",
  "Sacre Coeur - Glen Iris - 3146",
  "Sacred Heart College - Newtown - 3220",
  "Sacred Heart Girls' College - Oakleigh - 3166",
  "Sacred Heart School - Croydon - 3136",
  "Sacred Heart School - Diamond Creek - 3089",
  "Sacred Heart School - Fitzroy - 3065",
  "Sacred Heart School - Kew - 3101",
  "Sacred Heart School - Newport - 3015",
  "Sacred Heart School - Oakleigh - 3166",
  "Sacred Heart School - Preston - 3072",
  "Sacred Heart School - Sandringham - 3191",
  "Sacred Heart School - St Albans - 3021",
  "Salesian College Chadstone - Chadstone - 3148",
  "Salesian College Sunbury - Sunbury - 3429",
  "Saltwater P-9 College - Point Cook - 3030",
  "Sandringham College - Sandringham - 3191",
  "Sandringham College-Bluff Road 7-9 Campus - Sandringham - 3191",
  "Sandringham East Primary School - Sandringham - 3191",
  "Sandringham Primary School - Sandringham - 3191",
  "Santa Maria College - Northcote - 3070",
  "Sassafras Primary School - Sassafras - 3787",
  "School of the Good Shepherd - Gladstone Park - 3043",
  "Scoresby Primary School - Scoresby - 3179",
  "Scoresby Secondary College - Scoresby - 3179",
  "Scotch College - Hawthorn - 3122",
  "Seabrook Primary School - Seabrook - 3028",
  "Seaford North Primary School - Seaford - 3198",
  "Seaford Park Primary School - Seaford - 3198",
  "Seaford Primary School - Seaford - 3198",
  "Seaford Primary School-Seaford Special Assistance Unit - Seaford - 3198",
  "Seaholme Primary School - Seaholme - 3018",
  "SEDA College (Victoria) - AFL -  Sunshine - Sunshine - 3020",
  "SEDA College (Victoria) - AFL - Clayton - Clayton - 3168",
  "SEDA College (Victoria) - AFL-  Geelong - Geelong - 3219",
  "SEDA College (Victoria) - AFL - Werribee - Werribee - 3030",
  "SEDA College (Victoria) - AFL Dandenong Campus - Dandenong Oasis - Dandenong - 3175",
  "SEDA College (Victoria) - AFL- Preston - Preston - 3072",
  "SEDA College (Victoria) - AFL Victoria & Cricket Australia Sports Development Program - Strathmore - Strathmore - 3041",
  "SEDA College (Victoria) - Basketball - Dandenong - Dandenong - 3175",
  "SEDA College (Victoria) - Basketball Braybrook - Braybrook - 3019",
  "SEDA College (Victoria) - Basketball Broadmeadows - Broadmeadows - 3047",
  "SEDA College (Victoria) - Basketball Burwood - Burwood - 3151",
  "SEDA College (Victoria) - Building and Construction -  Deer Park - Deer Park - 3023",
  "SEDA College (Victoria) - Building and Construction - Dandenong - Dandenong - 3175",
  "SEDA College (Victoria) - BVNV Geelong - North Geelong - 3215",
  "SEDA College (Victoria) - Camberwell - 3123",
  "SEDA College (Victoria) - Cricket Australia -  Carlton - Carlton - 3054",
  "SEDA College (Victoria) - Cricket Australia - Box Hill - Box Hill - 3128",
  "SEDA College (Victoria) - Cricket Australia - Footscray - Footscray - 3011",
  "SEDA College (Victoria) - Cross Keys Reserve Campus - Hawthorn East - 3073",
  "SEDA College (Victoria) - FFV Burnley - Burnley - 3121",
  "SEDA College (Victoria) - FFV Burnley 2 - Burnley - 3121",
  "SEDA College (Victoria) - Frankston Park Function Centre - Frankston - 3199",
  "SEDA College (Victoria) - Hawthorn Talented Player Program (TPP) - Hawthorn - 3122",
  "SEDA College (Victoria) - J.E Moore Park Campus - Hawthorn East - 3073",
  "SEDA College (Victoria) - Jubilee Park - Albert Park - 3134",
  "SEDA College (Victoria) - MC North Melbourne YMCA - North Melbourne - 3051",
  "SEDA College (Victoria) - Melbourne City Talented Player Program - Kensington - Kensington - 3031",
  "SEDA College (Victoria) - Melbourne Sports Centres Parkville - Parkville - 3052",
  "SEDA College (Victoria) - Multi Geelong - Geelong - 3220",
  "SEDA College (Victoria) - Netball  - Keysborough - Keysborough - 3173",
  "SEDA College (Victoria) - Netball Ascot Vale - Ascot Vale - 3032",
  "SEDA College (Victoria) - Netball Burnley - Burnley - 3121",
  "SEDA College (Victoria) - Sailing - Albert Park - Albert Park - 3206",
  "SEDA College (Victoria) - The Huddle, North Melbourne Football Club - North Melbourne - 3051",
  "Selby Primary School - Selby - 3159",
  "Serpell Primary School - Templestowe - 3106",
  "Seville Primary School - Seville - 3139",
  "Shelford Girls' Grammar - Caulfield - 3161",
  "Sherbourne Primary School - Briar Hill - 3088",
  "Sherbrooke Community School - Sassafras - 3787",
  "Sholem Aleichem College - Elsternwick - 3185",
  "Sholem Aleichem College - Senior Campus - Elsternwick - 3185",
  "Sidrah Gardens School - Narre Warren North - 3804",
  "Siena College Ltd - Camberwell - 3124",
  "Silvan Primary School - Silvan - 3795",
  "Silverton Primary School - Noble Park North - 3174",
  "Simonds Catholic College - St Brigid's VCE Campus - Fitzroy North - 3068",
  "Simonds Catholic College - West Melbourne - 3003",
  "Sirius College - Broadmeadows - 3047",
  "Sirius College - Dallas Campus - Dallas - 3047",
  "Sirius College - Geelong Campus - North Geelong - 3214",
  "Sirius College - Ibrahim Dellal Campus - Sunshine West - 3020",
  "Sirius College - Keysborough Campus - Keysborough - 3173",
  "Sirius College - Meadow Fair Campus - Broadmeadows - 3047",
  "Skye Primary School - Skye - 3977",
  "Solway Primary School - Ashburton - 3147",
  "Somers Primary School - Somers - 3927",
  "Somers School Camp - Somers - 3927",
  "Somerville Primary School - Somerville - 3912",
  "Somerville Rise Primary School - Somerville - 3912",
  "Somerville Secondary College - Somerville - 3912",
  "Sophia Mundi Steiner School - Abbotsford - 3067",
  "Sorrento Primary School - Sorrento - 3943",
  "South Melbourne Park Primary School - Albert Park - 3206",
  "South Melbourne Primary School - Southbank - 3205",
  "South Oakleigh Secondary College - Oakleigh South - 3167",
  "South Yarra Primary School - South Yarra - 3141",
  "Southern Autistic School - East Bentleigh - 3165",
  "Southern Cross Grammar - Caroline Springs - 3023",
  "Southern Cross Primary School - Endeavour Hills - 3802",
  "Southmoor Primary School - Moorabbin - 3189",
  "Spensley Street Primary School - Clifton Hill - 3068",
  "Spotswood Primary School - Spotswood - 3015",
  "Spring Parks Primary School - Springvale - 3171",
  "Spring Parks Primary School-Valley Campus - Springvale South - 3172",
  "Springside Primary School - Caroline Springs - 3023",
  "Springside West Secondary College - Fraser Rise - 3336",
  "Springvale Park Special Developmental School - Springvale - 3171",
  "Springvale Rise Primary School - Springvale - 3171",
  "Springvale Rise Primary School-Springvale Road Campus - Springvale - 3171",
  "Ss Peter & Paul's School - Doncaster East - 3109",
  "St Agatha's School - Cranbourne - 3977",
  "St Agnes' School - Highett - 3190",
  "St Albans East Primary School - St Albans - 3021",
  "St Albans East Primary School-St Albans East Deaf Facility - St Albans - 3021",
  "St Albans Heights Primary School - St Albans - 3021",
  "St Albans Meadows Primary School - St Albans - 3021",
  "St Albans North Primary School - St Albans - 3021",
  "St Albans Primary School - St Albans - 3021",
  "St Albans Secondary College - St Albans - 3021",
  "St Aloysius College - North Melbourne - 3051",
  "St Andrews Christian College - Wantirna South - 3152",
  "St Andrew's School - Clayton South - 3169",
  "St Andrew's School - Werribee - 3030",
  "St Anne's School - Kew East - 3102",
  "St Anne's School - Park Orchards - 3114",
  "St Anne's School - Seaford - 3198",
  "St Anne's School - Sunbury - 3429",
  "St Anthony's School - Alphington - 3078",
  "St Anthony's School - Glen Huntly - 3163",
  "St Anthony's School - Lara - 3212",
  "St Anthony's School - Melton South - 3338",
  "St Anthony's School - Noble Park - 3174",
  "St Augustine's Primary School - Keilor - 3036",
  "St Augustine's School - Frankston - 3199",
  "St Augustine's School - Yarraville - 3013",
  "St Bede's College - Bentleigh East Campus - Bentleigh East - 3165",
  "St Bede's College - Mentone - 3194",
  "St Bede's School - Balwyn North - 3104",
  "St Bernadette's Catholic Primary School - The Basin - 3154",
  "St Bernadette's School - Ivanhoe - 3079",
  "St Bernadette's School - Sunshine North - 3020",
  "St Bernard's College - Essendon - 3040",
  "St Bernard's School - Bacchus Marsh - 3340",
  "St Bernard's School - Coburg - 3058",
  "St Brendan's School - Flemington - 3031",
  "St Brendan's School - Somerville - 3912",
  "St Bridget's School - Balwyn North - 3104",
  "St Brigid's School - Mordialloc - 3195",
  "St Brigid's School - Officer - 3809",
  "St Carlo Borromeo School - Greenvale - 3059",
  "St Catherine of Siena Catholic Primary School - Armstrong Creek - 3217",
  "St Catherine of Siena School - Melton West - 3337",
  "St Catherine's Primary School - Berwick - 3806",
  "St Catherine's School - Lalor - 3075",
  "St Catherine's School - Moorabbin - 3189",
  "St Catherine's School - Toorak - 3142",
  "St Cecilia's School - Glen Iris - 3146",
  "St Charles Borromeo School - Templestowe - 3106",
  "St Christopher's School - Airport West - 3042",
  "St Christopher's School - Glen Waverley - 3150",
  "St Clare's Catholic Primary School - Truganina - 3029",
  "St Clare's Primary School - Officer - 3809",
  "St Clare's School - Thomastown - 3074",
  "St Clement of Rome School - Bulleen - 3105",
  "St Columba's College - Essendon - 3040",
  "St Columba's School - Elwood - 3184",
  "St Damian's School - Bundoora - 3083",
  "St Dominic's School - Broadmeadows - 3047",
  "St Dominic's School - Camberwell - 3124",
  "St Dominic's School - Melton - 3337",
  "St Elizabeth's School - Dandenong North - 3175",
  "St Fidelis' School - Moreland - 3058",
  "St Finbar's School - Brighton East - 3187",
  "St Francis De Sales Catholic Primary School - Lynbrook - 3975",
  "St Francis de Sales School - Oak Park - 3046",
  "St Francis of Assisi Catholic Primary School - Tarneit - 3029",
  "St Francis of Assisi School - Mill Park - 3082",
  "St Francis Xavier College - Beaconsfield - 3807",
  "St Francis Xavier College - Berwick Campus - Berwick - 3806",
  "St Francis Xavier College - Officer Campus - Officer - 3809",
  "St Francis Xavier Primary School - Montmorency - 3094",
  "St Francis Xavier School - Corio - 3214",
  "St Francis Xavier School - Frankston - 3199",
  "St Francis Xavier's School - Box Hill - 3128",
  "St Gabriel's School - Reservoir - 3073",
  "St George Preca School - Caroline Springs - 3023",
  "St Gerard's School - Dandenong North - 3175",
  "St Gregory the Great School - Doncaster - 3108",
  "St Helena Secondary College - Eltham North - 3095",
  "St James' School - Brighton - 3186",
  "St James' School - Vermont - 3133",
  "St James the Apostle School - Hoppers Crossing - 3029",
  "St Joachim's School - Carrum Downs - 3201",
  "St Joan of Arc School - Brighton - 3186",
  "St John Bosco's School - Niddrie - 3042",
  "St John the Apostle Catholic Primary School - Tarneit - 3029",
  "St John the Baptist School - Ferntree Gully - 3156",
  "St John Vianney's School - Mulgrave - 3170",
  "St John Vianney's School - Parkdale - 3195",
  "St John XXIII Primary School - Thomastown - 3074",
  "St John's College Preston - Preston - 3072",
  "St John's Lutheran School Geelong - Geelong - 3220",
  "St John's Regional College - Dandenong - 3175",
  "St John's School - Clifton Hill - 3068",
  "St John's School - Footscray - 3011",
  "St John's School - Frankston East - 3199",
  "St John's School - Heidelberg - 3084",
  "St John's School - Mitcham - 3132",
  "St Joseph the Worker School - Reservoir - 3073",
  "St Joseph's College - Ferntree Gully - 3156",
  "St Joseph's College Geelong - Newtown - 3220",
  "St Joseph's College Geelong - Westcourt Campus - Herne Hill - 3218",
  "St Joseph's Flexible Learning Centre - Geelong Campus - Grovedale - 3216",
  "St Joseph's Flexible Learning Centre - North Melbourne - 3051",
  "St Joseph's Primary School - Boronia - 3155",
  "St Joseph's School - Black Rock - 3193",
  "St Joseph's School - Brunswick West - 3055",
  "St Joseph's School - Chelsea - 3196",
  "St Joseph's School - Collingwood - 3066",
  "St Joseph's School - Crib Point - 3919",
  "St Joseph's School - Elsternwick - 3185",
  "St Joseph's School - Hawthorn - 3122",
  "St Joseph's School - Malvern - 3144",
  "St Joseph's School - Mernda - 3754",
  "St Joseph's School - Northcote - 3070",
  "St Joseph's School - Sorrento - 3943",
  "St Joseph's School - Springvale - 3171",
  "St Jude the Apostle School - Scoresby - 3179",
  "St Jude's School - Langwarrin - 3910",
  "St Justin's School - Wheelers Hill - 3150",
  "St Kevin's College - Glendalough - Toorak - 3142",
  "St Kevin's College - Toorak - 3142",
  "St Kevin's College - Waterford - Richmond - 3121",
  "St Kevin's School - Hampton Park - 3976",
  "St Kevin's School - Templestowe - 3107",
  "St Kilda Park Primary School - St Kilda - 3182",
  "St Kilda Primary School - St Kilda - 3182",
  "St Lawrence Catholic Primary School - Derrimut - 3030",
  "St Lawrence of Brindisi Catholic Primary School - Weir Views - 3338",
  "St Leo the Great Primary School - Altona North - 3025",
  "St Leonard's College - Brighton East - 3187",
  "St Leonard's School - Glen Waverley - 3150",
  "St Louis de Montfort's School - Aspendale - 3195",
  "St Luke the Evangelist School - Blackburn South - 3130",
  "St Luke's School - Lalor - 3075",
  "St Luke's School - Wantirna - 3152",
  "St Macartan's School - Mornington - 3931",
  "St Margaret Mary's School - Brunswick North - 3056",
  "St Margaret Mary's School - Spotswood - 3015",
  "St Margaret’s Berwick Grammar - Berwick - 3806",
  "St Margaret’s Berwick Grammar - Berwick Grammar School - Officer - 3809",
  "St Margaret's Primary School - Maribyrnong - 3032",
  "St Margaret's School - East Geelong - 3219",
  "St Mark's School - Dingley Village - 3172",
  "St Mark's School - Fawkner - 3060",
  "St Martin de Porres School - Avondale Heights - 3034",
  "St Martin de Porres School - Laverton - 3028",
  "St Martin of Tours School - Rosanna - 3084",
  "St Mary MacKillop Primary School - Keilor Downs - 3038",
  "St Mary Magdalen’s School - Chadstone - 3148",
  "St Mary of the Cross Catholic Primary School - Point Cook - 3030",
  "St Mary of the Cross MacKillop Catholic Parish Primary School - Epping - 3076",
  "St Mary’s College for the Deaf – Dandenong Campus - Dandenong - 3175",
  "St Mary’s College for the Deaf – Ringwood Campus - Ringwood - 3134",
  "St Mary’s College for the Deaf – South Morang Campus - South Morang - 3752",
  "St Mary’s College for the Deaf – Sunbury Campus - Sunbury - 3429",
  "St Mary’s College Melbourne - Edmund Rice Campus - St Kilda East - 3183",
  "St Mary’s College Melbourne - Presentation Campus - St Kilda - 3181",
  "St Mary's College for the Deaf - Tarneit Campus - Tarneit - 3029",
  "St Mary's College for the Deaf - Wantirna South - 3152",
  "St Mary's Coptic Orthodox College - Coolaroo - 3048",
  "St Mary's School - Altona - 3018",
  "St Mary's School - Ascot Vale - 3032",
  "St Mary's School - Campus 2 - St Kilda East - 3183",
  "St Mary's School - Dandenong - 3175",
  "St Mary's School - Geelong - 3220",
  "St Mary's School - Greensborough - 3088",
  "St Mary's School - Hampton - 3188",
  "St Mary's School - Hastings - 3915",
  "St Mary's School - Malvern East - 3145",
  "St Mary's School - Mount Evelyn - 3796",
  "St Mary's School - St Kilda East - 3183",
  "St Mary's School - Thornbury - 3071",
  "St Mary's School - Williamstown - 3016",
  "St Matthew's School - Fawkner - 3060",
  "St Michael's Grammar School - St Kilda - 3182",
  "St Michael's Primary School - North Melbourne - 3051",
  "St Michael's School - Ashburton - 3147",
  "St Michael's School - Berwick - 3806",
  "St Monica's College - Dalton Road Campus - Epping - 3076",
  "St Monica's College - Epping - 3076",
  "St Monica's Primary School - Moonee Ponds - 3039",
  "St Monica's School - Footscray - 3011",
  "St Oliver Plunkett's School - Pascoe Vale - 3044",
  "St Patrick's School - Geelong West - 3218",
  "St Patrick's School - Lilydale - 3140",
  "St Patrick's School - Mentone - 3194",
  "St Patrick's School - Murrumbeena - 3163",
  "St Patrick's School - Pakenham - 3810",
  "St Paul Apostle North School - Endeavour Hills - 3802",
  "St Paul Apostle South School - Endeavour Hills - 3802",
  "St Paul the Apostle Catholic Primary School - Doreen - 3754",
  "St Paul's College - Balwyn - 3101",
  "St Paul's Kealba Catholic School - Kealba - 3021",
  "St Paul's School - Bentleigh - 3204",
  "St Paul's School - Coburg - 3058",
  "St Paul's School - Monbulk - 3793",
  "St Paul's School - Sunshine West - 3020",
  "St Peter Apostle School - Hoppers Crossing - 3029",
  "St Peter Chanel School - Deer Park - 3023",
  "St Peter Julian Eymard - Mooroolbark - 3138",
  "St Peter's College - Clyde North Campus - Cranbourne East - 3977",
  "St Peter's College - Cranbourne - 3977",
  "St Peter's School - Bentleigh East - 3165",
  "St Peter's School - Clayton - 3168",
  "St Peter's School - Epping - 3076",
  "St Peter's School - Keilor East - 3033",
  "St Peter's School - Sunshine West - 3020",
  "St Philip's School - Blackburn North - 3130",
  "St Pius X School - Heidelberg West - 3081",
  "St Raphael's School - Preston West - 3072",
  "St Richard's Primary School - Kilsyth - 3137",
  "St Robert's School - Newtown - 3220",
  "St Roch's School - Glen Iris - 3146",
  "St Scholastica's School - Bennettswood - 3125",
  "St Simon's School - Rowville - 3178",
  "St Stephen's School - Reservoir - 3073",
  "St Theresa's School - Albion - 3020",
  "St Therese's School - Cranbourne - 3977",
  "St Therese's School - Essendon - 3040",
  "St Thomas Aquinas School - Norlane - 3214",
  "St Thomas More's School - Belgrave - 3160",
  "St Thomas More's School - Hadfield - 3046",
  "St Thomas More's School - Mount Eliza - 3930",
  "St Thomas the Apostle Catholic Primary School - Cranbourne East - 3977",
  "St Thomas the Apostle School - Blackburn - 3130",
  "St Thomas the Apostle School - Greensborough - 3088",
  "St Timothy's School - Vermont - 3133",
  "St Vincent de Paul's School - Strathmore - 3041",
  "Star of the Sea College - Brighton - 3186",
  "Staughton College - Melton South - 3338",
  "Stella Maris Catholic Primary School - Point Cook - 3030",
  "Stella Maris School - Beaumaris - 3193",
  "Stevensville Primary School - St Albans - 3021",
  "Stott's Colleges - Melbourne - 3000",
  "Strathaird Primary School - Narre Warren South - 3805",
  "Strathcona Baptist Girls' Grammar - Canterbury - 3126",
  "Strathcona Baptist Girls' Grammar - Hawthorn Campus - Hawthorn - 3122",
  "Strathcona Baptist Girls' Grammar - Primary Campus - Canterbury - 3126",
  "Strathmore North Primary School - Strathmore - 3041",
  "Strathmore Primary School - Strathmore - 3041",
  "Strathmore Secondary College - Strathmore - 3041",
  "Strathtulloh Primary School - Strathtulloh - 3338",
  "Streeton Primary School - Yallambie - 3085",
  "Sunbury And Macedon Ranges Specialist School - Sunbury - 3429",
  "Sunbury College - Sunbury - 3429",
  "Sunbury Downs Secondary College - Sunbury - 3429",
  "Sunbury Heights Primary School - Sunbury - 3429",
  "Sunbury Primary School - Sunbury - 3429",
  "Sunbury West Primary School - Sunbury - 3429",
  "Sunshine Christian School - Sunshine North - 3020",
  "Sunshine College - Sunshine West - 3020",
  "Sunshine College-North Sunshine Campus - Sunshine North - 3020",
  "Sunshine College-Sunshine Western Region Deaf Facility - Sunshine - 3022",
  "Sunshine College-Sunshine Work Education Training Unit - Sunshine - 3020",
  "Sunshine Harvester Primary School - Sunshine - 3020",
  "Sunshine Heights Primary School - Sunshine - 3020",
  "Sunshine North Primary School - Sunshine North - 3020",
  "Sunshine Primary School - Sunshine - 3020",
  "Sunshine Special Developmental School - Sunshine - 3020",
  "Surrey Hills Primary School - Surrey Hills - 3127",
  "Suzanne Cory High School - Werribee - 3030",
  "Swinburne Senior Secondary College - Hawthorn - 3122",
  "Swinburne Senior Secondary College-Camberwell Road Campus - Hawthorn East - 3123",
  "Sydenham - Hillside Primary School - Sydenham - 3037",
  "Sydenham - Hillside Primary School-Hillside Campus - Hillside - 3037",
  "Sydney Road Community School - Brunswick - 3056",
  "Syndal South Primary School - Mount Waverley - 3149",
  "Tarneit P-9 College - Tarneit - 3029",
  "Tarneit Rise Primary School - Tarneit - 3029",
  "Tarneit Senior College - Tarneit - 3029",
  "Tate Street Primary School Geelong - Geelong East - 3219",
  "Taylors Hill Primary School - Taylors Hill - 3037",
  "Taylors Lakes Primary School - Taylors Lakes - 3038",
  "Taylors Lakes Secondary College - Taylors Lakes - 3038",
  "Tecoma Primary School - Tecoma - 3160",
  "Templestowe College - Templestowe Lower - 3107",
  "Templestowe Heights Primary School - Templestowe Lower - 3107",
  "Templestowe Park Primary School - Templestowe - 3106",
  "Templestowe Valley Primary School - Lower Templestowe - 3107",
  "Templeton Primary School - Wantirna - 3152",
  "The Basin Primary School - The Basin - 3154",
  "The Currajong School - Malvern East - 3145",
  "The Geelong College - Newtown - 3220",
  "The Geelong College Preparatory School - Newtown - 3220",
  "The Grange P-12 College - Hoppers Crossing - 3029",
  "The King David School - Armadale - 3143",
  "The King David School - Junior School - Armadale - 3143",
  "The King David School - The Rebecca Magid Centre - Armadale - 3143",
  "The Knox School - Wantirna South - 3152",
  "The Lakes South Morang College - South Morang - 3752",
  "The Lakes South Morang College-Primary Campus - South Morang - 3752",
  "The Patch Primary School - The Patch - 3792",
  "Thomas Carr College - Tarneit - 3029",
  "Thomas Chirnside Primary School - Werribee - 3030",
  "Thomas Mitchell Primary School - Endeavour Hills - 3802",
  "Thomastown East Primary School - Thomastown - 3074",
  "Thomastown Meadows Primary School - Thomastown - 3074",
  "Thomastown Primary School - Thomastown - 3074",
  "Thomastown Secondary College - Thomastown - 3074",
  "Thomastown West Primary School - Thomastown - 3074",
  "Thornbury High School - Thornbury - 3071",
  "Thornbury Primary School - Thornbury - 3071",
  "Timbarra P-9 College - Berwick - 3806",
  "Tintern Grammar - Ringwood East - 3135",
  "Tinternvale Primary School - Ringwood East - 3135",
  "Tombolo Academy - Hampton - 3188",
  "Toolern Vale and District Primary School - Toolern Vale - 3337",
  "Toorak College - Mount Eliza - 3930",
  "Toorak Primary School - Toorak - 3142",
  "Tootgarook Primary School - Tootgarook - 3941",
  "Travancore School - Travancore - 3032",
  "Travancore School-Parkville Campus - Parkville - 3052",
  "Trinity Catholic Primary School - Narre Warren - 3805",
  "Trinity Catholic School - Richmond - 3121",
  "Trinity Grammar School Kew - Kew - 3101",
  "Truganina P-9 College - Truganina - 3029",
  "Truganina South Primary School - Truganina - 3029",
  "Tucker Road Bentleigh Primary School - Bentleigh - 3204",
  "Tullamarine Primary School - Tullamarine - 3043",
  "Tulliallan Primary School - Cranbourne North - 3977",
  "Tyabb Primary School - Tyabb - 3913",
  "Tyabb Railway Station Primary School - Tyabb - 3913",
  "University High School - Parkville - 3052",
  "University High School-Elizabeth Blackburn School of Sciences - Parkville - 3031",
  "University Park Primary School - St Albans - 3021",
  "Upper Ferntree Gully Primary School - Upper Ferntree Gully - 3156",
  "Upwey High School - Upwey - 3158",
  "Upwey Primary School - Upwey - 3158",
  "Upwey South Primary School - Upwey - 3158",
  "Valkstone Primary School - Bentleigh East - 3165",
  "Vermont Primary School - Vermont - 3133",
  "Vermont Secondary College - Vermont - 3133",
  "Vermont South Special School - Vermont South - 3133",
  "Victoria Road Primary School - Lilydale - 3140",
  "Victoria University Secondary College - St Albans - 3021",
  "Victoria University Secondary College-Cairnlea Campus - Cairnlea - 3023",
  "Victoria University Secondary College-Deer Park Campus - Deer Park - 3023",
  "Victorian College For The Deaf - Melbourne - 3000",
  "Victorian College Of The Arts Secondary School - Southbank - 3006",
  "Victorian School Of Languages - Thornbury - 3071",
  "Viewbank College - Viewbank - 3084",
  "Viewbank Primary School - Viewbank - 3084",
  "Village School - Croydon North - 3136",
  "Virtual School Victoria - Thornbury - 3071",
  "Wales Street Primary School - Thornbury - 3071",
  "Wallan Primary School - Wallan - 3756",
  "Wallan Secondary College - Wallan - 3756",
  "Wallarano Primary School - Noble Park - 3174",
  "Wallaroo Primary School - Hastings - 3915",
  "Wandin North Primary School - Wandin North - 3139",
  "Wandin Yallock Primary School - Wandin North - 3139",
  "Wangala Primary School - Belmont - 3216",
  "Wantirna College - Wantirna - 3152",
  "Wantirna Primary School - Wantirna - 3152",
  "Wantirna South Primary School - Wantirna South - 3152",
  "Waratah Special Developmental School - Bellfield - 3081",
  "Warrandyte High School - Warrandyte - 3113",
  "Warrandyte Primary School - Warrandyte - 3113",
  "Warranwood Primary School - Warranwood - 3134",
  "Warringa Park School - Hoppers Crossing - 3029",
  "Warringa Park School-Bethany Road Campus - Hoppers Crossing - 3029",
  "Warringa Park School-Cayleys Road Campus - Werribee South - 3030",
  "Watsonia Heights Primary School - Greensborough - 3088",
  "Watsonia North Primary School - Watsonia North - 3087",
  "Watsonia Primary School - Watsonia - 3087",
  "Wattle Glen Primary School - Wattle Glen - 3096",
  "Wattle Park Primary School - Burwood - 3125",
  "Wattle View Primary School - Ferntree Gully - 3156",
  "Waverley Christian College - Narre Warren South Campus - Narre Warren South - 3805",
  "Waverley Christian College - Wantirna South - 3152",
  "Waverley Meadows Primary School - Wheelers Hill - 3150",
  "Wedge Park Primary School - Melton West - 3337",
  "Weeden Heights Primary School - Vermont South - 3133",
  "Wellington Secondary College - Mulgrave - 3170",
  "Wembley Primary School - Yarraville - 3013",
  "Werribee Primary School - Werribee - 3030",
  "Werribee Secondary College - Werribee - 3030",
  "Wesley College - Elsternwick Campus - Elsternwick - 3185",
  "Wesley College - Glen Waverley Campus - Glen Waverley - 3150",
  "Wesley College - Melbourne - 3004",
  "Wesley College - St Kilda Road Junior Campus - Windsor - 3181",
  "Westall Primary School - Clayton South - 3169",
  "Westall Secondary College - Clayton South - 3169",
  "Westall Secondary College-LEEP Chelsea - Chelsea - 3196",
  "Westall Secondary College-Westall English Language Centre - Clayton South - 3169",
  "Westbourne Grammar School - Newport - 3015",
  "Westbourne Grammar School - Truganina - 3029",
  "Westbreen Primary School - Pascoe Vale - 3044",
  "Western Autistic School - Laverton - 3028",
  "Western English Language School - Braybrook - 3019",
  "Western English Language School-Footscray Campus - Footscray - 3011",
  "Western English Language School-Manor Lakes Campus - Wyndham Vale - 3024",
  "Western English Language School-Wyndham Secondary Campus - Werribee - 3030",
  "Western Heights Secondary College - Hamlyn Heights - 3215",
  "Western Heights Secondary College-Quamby Campus - Hamlyn Heights - 3215",
  "Western Port Secondary College - Hastings - 3915",
  "Westgarth Primary School - Northcote - 3070",
  "Westgrove Primary School - Werribee - 3030",
  "Westmeadows Primary School - Westmeadows - 3049",
  "Wheelers Hill Primary School - Wheelers Hill - 3150",
  "Wheelers Hill Secondary College - Wheelers Hill - 3150",
  "Whitefriars College Inc - Donvale - 3111",
  "Whitehorse Primary School - Blackburn North - 3130",
  "Whittington Primary School - Whittington - 3219",
  "Wilandra Rise Primary School - Clyde North - 3978",
  "William Ruthven Primary School - Reservoir - 3073",
  "William Ruthven Secondary College - Reservoir - 3073",
  "Williamstown High School - Williamstown - 3016",
  "Williamstown High School-Bayview Campus - Williamstown - 3016",
  "Williamstown North Primary School - Williamstown - 3016",
  "Williamstown Primary School - Williamstown - 3016",
  "Willmott Park Primary School - Craigieburn - 3064",
  "Willmott Park Primary School-Willmott Park Deaf Facility - Craigieburn - 3064",
  "Windsor Primary School - Windsor - 3181",
  "Wollert Primary School - Wollert - 3750",
  "Wonga Park Primary School - Wonga Park - 3115",
  "Woodlands Primary School - Langwarrin - 3910",
  "Woodleigh School - Langwarrin South - 3911",
  "Woodleigh School - Minimbah Campus - Frankston South - 3199",
  "Woodleigh School - Penbank Campus - Moorooduc - 3933",
  "Woodville Primary School - Hoppers Crossing - 3029",
  "Wooranna Park Primary School - Dandenong - 3175",
  "Wyndham Central Secondary College - Werribee - 3030",
  "Wyndham Park Primary School - Werribee - 3030",
  "Wyndham Vale Primary School - Wyndham Vale - 3024",
  "Xavier College - Billilla Annex Campus - Brighton - 3186",
  "Xavier College - Burke Hall - Kew - 3101",
  "Xavier College - Kew - 3101",
  "Xavier College - Kostka Hall - Brighton - 3186",
  "Yarra Hills Secondary College - Mooroolbark - 3138",
  "Yarra Hills Secondary College-Mount Evelyn Campus - Mount Evelyn - 3796",
  "Yarra Me School - Preston - 3072",
  "Yarra Me School -Hurstbridge Farm Campus - Nutfield - 3099",
  "Yarra Primary School - Richmond - 3121",
  "Yarra Ranges Special Developmental School - Mount Evelyn - 3796",
  "Yarra Road Primary School - Croydon - 3136",
  "Yarra Valley Grammar - Ringwood - 3134",
  "Yarrabah School - Aspendale - 3195",
  "Yarraman Oaks Primary School - Noble Park - 3174",
  "Yarrambat Primary School - Yarrambat - 3091",
  "Yarraville Special Developmental School - Yarraville - 3013",
  "Yarraville West Primary School - Yarraville - 3013",
  "Yea High School-Chinese Community Centre - Bayswater - 3153",
  "Yea High School-Eltham Birribi - Eltham - 3095",
  "Yea High School-Goldsworthy Road Campus - Corio - 3214",
  "Yea High School-Kevin Collopy Pavilion - Frankston - 3199",
  "Yea High School-Memorial Hall campus - Epping - 3076",
  "Yea High School-The Briars - Mount Martha - 3934",
  "Yering Primary School - Yering - 3770",
  "Yeshivah College - St Kilda East - 3183",
  "Yesodei HaTorah College - Brighton Campus - Ormond - 3204",
  "Yesodei HaTorah College - Elwood - 3184",
  "Youth2Industry College - South Melbourne - 3205"
];
